{
//////////////////////////////////////////////////////////
//   This file has been automatically generated 
//     (Wed Jul 15 20:21:08 2020 by ROOT version5.34/20)
//   from TTree tree/Analysed Tree:raw,cal,analysed
//   found on file: run0127_analysed.root_test
//////////////////////////////////////////////////////////


//Reset ROOT and connect tree file
   gROOT->Reset();
   TFile *f = (TFile*)gROOT->GetListOfFiles()->FindObject("run0127_analysed.root_test");
   if (!f) {
      f = new TFile("run0127_analysed.root_test");
   }
    f->GetObject("tree",tree);

//Declaration of leaves types
   Int_t           RunNumber;
   Long64_t        EventNumber;
   Int_t           CoincidenceTrigger;
   Int_t           Trig_DSB;
   Int_t           Trig_BxESPRIxTEL;
   Int_t           Trig_BxESPRI;
   Int_t           Trig_BxTEL;
   Int_t           Trig_BxHODP;
   Int_t           Trig_BxHODF;
   Int_t           Trig_BxNEBULA;
   Int_t           F3TRaw[2];
   Int_t           F3QRaw[2];
   Double_t        F3TCal[2];
   Double_t        F3QCal[2];
   Double_t        F3T;
   Double_t        F3Q;
   Int_t           F7TRaw[2];
   Int_t           F7QRaw[2];
   Double_t        F7TCal[2];
   Double_t        F7QCal[2];
   Double_t        F7T;
   Double_t        F7Q;
   Int_t           SBT1TRaw[2];
   Int_t           SBT1QRaw[2];
   Double_t        SBT1TCal[2];
   Double_t        SBT1QCal[2];
   Double_t        SBT1T;
   Double_t        SBT1Q;
   Int_t           SBT2TRaw[2];
   Int_t           SBT2QRaw[2];
   Double_t        SBT2TCal[2];
   Double_t        SBT2QCal[2];
   Double_t        SBT2T;
   Double_t        SBT2Q;
   Double_t        F13T;
   Double_t        F13Q;
   Int_t           SBVTRaw[2];
   Int_t           SBVQRaw[2];
   Double_t        SBVTCal[2];
   Double_t        SBVQCal[2];
   Double_t        SBVT;
   Double_t        SBVQ;
   Double_t        TOF37;
   Double_t        Beta37;
   Double_t        Gamma37;
   Double_t        Ek37;
   Double_t        TOF713;
   Double_t        Beta713;
   Double_t        Gamma713;
   Double_t        Ek713;
   Int_t           BDC1_nhits;
   vector<double>  BDC1_TDC;
   vector<double>  BDC1_layerid;
   vector<double>  BDC1_wireid;
   vector<int>     BDC1_layer_hits;
   Int_t           BDC1_nlayerx;
   Int_t           BDC1_nlayery;
   vector<double>  BDC1_Track_dl;
   vector<double>  BDC1_Track_XY;
   vector<double>  BDC1_Track_Z;
   vector<double>  BDC1_Track_dXY;
   Double_t        BDC1_X;
   Double_t        BDC1_Y;
   Double_t        BDC1_ThetaX;
   Double_t        BDC1_ThetaY;
   Int_t           BDC2_nhits;
   vector<double>  BDC2_TDC;
   vector<double>  BDC2_layerid;
   vector<double>  BDC2_wireid;
   vector<int>     BDC2_layer_hits;
   Int_t           BDC2_nlayerx;
   Int_t           BDC2_nlayery;
   vector<double>  BDC2_Track_dl;
   vector<double>  BDC2_Track_XY;
   vector<double>  BDC2_Track_Z;
   vector<double>  BDC2_Track_dXY;
   Double_t        BDC2_X;
   Double_t        BDC2_Y;
   Double_t        BDC2_ThetaX;
   Double_t        BDC2_ThetaY;
   Double_t        beamFL;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   Int_t           FDC0_nhits;
   vector<double>  FDC0_TDC;
   vector<double>  FDC0_layerid;
   vector<double>  FDC0_wireid;
   vector<int>     FDC0_layer_hits;
   Int_t           FDC0_nlayerx;
   Int_t           FDC0_nlayery;
   vector<double>  FDC0_Track_dl;
   vector<double>  FDC0_Track_XY;
   vector<double>  FDC0_Track_Z;
   vector<double>  FDC0_Track_dXY;
   Double_t        FDC0_X;
   Double_t        FDC0_Y;
   Double_t        FDC0_ThetaX;
   Double_t        FDC0_ThetaY;
   Double_t        fdc0Angle;
   Double_t        fdc0Phi;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   Int_t           dssdQRaw[4][32];
   Int_t           dssdTRaw[2][32];
   Int_t           csiQRaw[7];
   Double_t        csiQPed[7];
   Int_t           RefTime1;
   Int_t           RefTime2;
   Double_t        dssdQPed[4][32];
   Double_t        csiQPed[7];
   Int_t           dssdQHit;
   Int_t           dssdQHitSide[0];
   Int_t           dssdQHitStripId[0];
   Double_t        dssdQHitQPed[0];
   Int_t           dssdTHit;
   Int_t           dssdTHitSide[0];
   Int_t           dssdTHitStripId[0];
   Double_t        dssdTHitTCal[0];
   Int_t           dssdHit;
   Int_t           dssdHitSide[0];
   Int_t           dssdHitFid[0];
   Int_t           dssdHitBid[0];
   Double_t        dssdHitFQPed[0];
   Double_t        dssdHitBQPed[0];
   Double_t        dssdHitTCal[0];
   Int_t           csiQHit;
   Int_t           csiQHitId[0];
   Double_t        csiQHitQPed[0];
   Int_t           csiTHit;
   Int_t           csiTHitId[0];
   Double_t        csiTHitTCal[0];
   Int_t           csiHit;
   Int_t           csiHitId[0];
   Double_t        csiHitQPed[0];
   Double_t        csiHitTCal[0];
   Int_t           teleHit;
   Int_t           teleHitSide[0];
   Int_t           teleHitFid[0];
   Int_t           teleHitBid[0];
   Double_t        teleHitDssdFQPed[0];
   Double_t        teleHitDssdBQPed[0];
   Double_t        teleHitDssdTCal[0];
   Int_t           teleHitCid[0];
   Double_t        teleHitCsiQPed[0];
   Double_t        teleHitCsiTCal[0];
   Double_t        teleHitDssdFE[0];
   Double_t        teleHitDssdBE[0];
   Double_t        teleHitCsiE[0];
   Int_t           bestHit;
   Double_t        teleCsiE;
   Double_t        teleCsiE_sync;
   Double_t        teleDssdFE;
   Double_t        teleDssdBE;
   Double_t        teleDssdFE_old;
   Double_t        teleDssdBE_old;
   Double_t        teleDssdE;
   Double_t        teleDssdMaxE;
   Double_t        teleCsiT;
   Double_t        teleDssdT;
   Double_t        teleEnergy;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   Double_t        teleAngle;
   Double_t        telePhi;
   Double_t        teleLocusAngle;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   Int_t           hodNHit;
   Int_t           hodID[40];
   Int_t           hodTRaw[2][40];
   Int_t           hodQRaw[2][40];
   Double_t        hodQPed[2][40];
   Double_t        hodTCal[2][40];
   Double_t        hodQCal[2][40];
   Double_t        hodBarTCal[40];
   Double_t        hodBarQCal[40];
   Int_t           EventNumber;
   Int_t           RunNumber;
   vector<int>     plasTdcRaw0;
   vector<int>     plasTdcRaw1;
   vector<int>     plasTdcRaw2;
   vector<int>     plasTdcRaw3;
   vector<int>     rdcTdc;
   vector<int>     rdcPlaneId;
   vector<int>     rdcWireId;
   vector<int>     rdcPlaneNHit;
   Int_t           naiQRaw[4][7];
   Int_t           plasQRaw[4];
   Int_t           plasTRaw[4];
   Int_t           plasTimeRef;
   Double_t        rdcX[2];
   Double_t        rdcY[2];
   Double_t        rdcA[2];
   Double_t        rdcB[2];
   Double_t        rdcChi2[2];
   Double_t        rdcDL[2][7];
   Double_t        rdcTch[2][7];
   Double_t        rdcRes[2][7];
   Double_t        naiQPed[4][7];
   Double_t        plasQPed[4];
   Int_t           rdcHit;
   Int_t           rdcHitSide[0];
   Int_t           naiHit;
   Int_t           naiHitSide[0];
   Int_t           naiHitBarId[0];
   Int_t           plasHit;
   Int_t           plasHitSide[0];
   Int_t           plasTHit;
   Int_t           plasQHit;
   Int_t           espriHit;
   Int_t           espriSide;
   Double_t        espriRdcX;
   Double_t        espriRdcY;
   Double_t        espriPlasQPed;
   Int_t           espriNaiBarId;
   Double_t        espriNaiQPed;
   Double_t        espriPlasT;
   Double_t        espriPlasE_Birks;
   Double_t        espriPlasE;
   Double_t        espriNaiE;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   Double_t        espriFL;
   Double_t        espriLocusAngle;
   Double_t        espriAngle;
   Double_t        espriPhi;
   Double_t        beamEnergy;
   Double_t        beamBeta;
   Double_t        tofSBTTarget;
   Double_t        ppDegraderE;
   Double_t        ppPlasE;
   Double_t        ppWinE;
   Double_t        ppShtE;
   Double_t        degraderThickness;
   Double_t        protonEnergy;
   Double_t        apDssdE;
   Double_t        apDegraderE;
   Double_t        apWinE;
   Double_t        alphaEnergy_old;
   Double_t        alphaEnergy;

   // Set branch addresses.
   tree->SetBranchAddress("RunNumber",&RunNumber);
   tree->SetBranchAddress("EventNumber",&EventNumber);
   tree->SetBranchAddress("CoincidenceTrigger",&CoincidenceTrigger);
   tree->SetBranchAddress("Trig_DSB",&Trig_DSB);
   tree->SetBranchAddress("Trig_BxESPRIxTEL",&Trig_BxESPRIxTEL);
   tree->SetBranchAddress("Trig_BxESPRI",&Trig_BxESPRI);
   tree->SetBranchAddress("Trig_BxTEL",&Trig_BxTEL);
   tree->SetBranchAddress("Trig_BxHODP",&Trig_BxHODP);
   tree->SetBranchAddress("Trig_BxHODF",&Trig_BxHODF);
   tree->SetBranchAddress("Trig_BxNEBULA",&Trig_BxNEBULA);
   tree->SetBranchAddress("F3TRaw",F3TRaw);
   tree->SetBranchAddress("F3QRaw",F3QRaw);
   tree->SetBranchAddress("F3TCal",F3TCal);
   tree->SetBranchAddress("F3QCal",F3QCal);
   tree->SetBranchAddress("F3T",&F3T);
   tree->SetBranchAddress("F3Q",&F3Q);
   tree->SetBranchAddress("F7TRaw",F7TRaw);
   tree->SetBranchAddress("F7QRaw",F7QRaw);
   tree->SetBranchAddress("F7TCal",F7TCal);
   tree->SetBranchAddress("F7QCal",F7QCal);
   tree->SetBranchAddress("F7T",&F7T);
   tree->SetBranchAddress("F7Q",&F7Q);
   tree->SetBranchAddress("SBT1TRaw",SBT1TRaw);
   tree->SetBranchAddress("SBT1QRaw",SBT1QRaw);
   tree->SetBranchAddress("SBT1TCal",SBT1TCal);
   tree->SetBranchAddress("SBT1QCal",SBT1QCal);
   tree->SetBranchAddress("SBT1T",&SBT1T);
   tree->SetBranchAddress("SBT1Q",&SBT1Q);
   tree->SetBranchAddress("SBT2TRaw",SBT2TRaw);
   tree->SetBranchAddress("SBT2QRaw",SBT2QRaw);
   tree->SetBranchAddress("SBT2TCal",SBT2TCal);
   tree->SetBranchAddress("SBT2QCal",SBT2QCal);
   tree->SetBranchAddress("SBT2T",&SBT2T);
   tree->SetBranchAddress("SBT2Q",&SBT2Q);
   tree->SetBranchAddress("F13T",&F13T);
   tree->SetBranchAddress("F13Q",&F13Q);
   tree->SetBranchAddress("SBVTRaw",SBVTRaw);
   tree->SetBranchAddress("SBVQRaw",SBVQRaw);
   tree->SetBranchAddress("SBVTCal",SBVTCal);
   tree->SetBranchAddress("SBVQCal",SBVQCal);
   tree->SetBranchAddress("SBVT",&SBVT);
   tree->SetBranchAddress("SBVQ",&SBVQ);
   tree->SetBranchAddress("TOF37",&TOF37);
   tree->SetBranchAddress("Beta37",&Beta37);
   tree->SetBranchAddress("Gamma37",&Gamma37);
   tree->SetBranchAddress("Ek37",&Ek37);
   tree->SetBranchAddress("TOF713",&TOF713);
   tree->SetBranchAddress("Beta713",&Beta713);
   tree->SetBranchAddress("Gamma713",&Gamma713);
   tree->SetBranchAddress("Ek713",&Ek713);
   tree->SetBranchAddress("BDC1_nhits",&BDC1_nhits);
   tree->SetBranchAddress("BDC1_TDC",&BDC1_TDC);
   tree->SetBranchAddress("BDC1_layerid",&BDC1_layerid);
   tree->SetBranchAddress("BDC1_wireid",&BDC1_wireid);
   tree->SetBranchAddress("BDC1_layer_hits",&BDC1_layer_hits);
   tree->SetBranchAddress("BDC1_nlayerx",&BDC1_nlayerx);
   tree->SetBranchAddress("BDC1_nlayery",&BDC1_nlayery);
   tree->SetBranchAddress("BDC1_Track_dl",&BDC1_Track_dl);
   tree->SetBranchAddress("BDC1_Track_XY",&BDC1_Track_XY);
   tree->SetBranchAddress("BDC1_Track_Z",&BDC1_Track_Z);
   tree->SetBranchAddress("BDC1_Track_dXY",&BDC1_Track_dXY);
   tree->SetBranchAddress("BDC1_X",&BDC1_X);
   tree->SetBranchAddress("BDC1_Y",&BDC1_Y);
   tree->SetBranchAddress("BDC1_ThetaX",&BDC1_ThetaX);
   tree->SetBranchAddress("BDC1_ThetaY",&BDC1_ThetaY);
   tree->SetBranchAddress("BDC2_nhits",&BDC2_nhits);
   tree->SetBranchAddress("BDC2_TDC",&BDC2_TDC);
   tree->SetBranchAddress("BDC2_layerid",&BDC2_layerid);
   tree->SetBranchAddress("BDC2_wireid",&BDC2_wireid);
   tree->SetBranchAddress("BDC2_layer_hits",&BDC2_layer_hits);
   tree->SetBranchAddress("BDC2_nlayerx",&BDC2_nlayerx);
   tree->SetBranchAddress("BDC2_nlayery",&BDC2_nlayery);
   tree->SetBranchAddress("BDC2_Track_dl",&BDC2_Track_dl);
   tree->SetBranchAddress("BDC2_Track_XY",&BDC2_Track_XY);
   tree->SetBranchAddress("BDC2_Track_Z",&BDC2_Track_Z);
   tree->SetBranchAddress("BDC2_Track_dXY",&BDC2_Track_dXY);
   tree->SetBranchAddress("BDC2_X",&BDC2_X);
   tree->SetBranchAddress("BDC2_Y",&BDC2_Y);
   tree->SetBranchAddress("BDC2_ThetaX",&BDC2_ThetaX);
   tree->SetBranchAddress("BDC2_ThetaY",&BDC2_ThetaY);
   tree->SetBranchAddress("beamFL",&beamFL);
   tree->SetBranchAddress("vBeam",&vBeam);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("bdc1Position",&bdc1Position);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("bdc2Position",&bdc2Position);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("targetPosition",&targetPosition);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("sbtPosition",&sbtPosition);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("FDC0_nhits",&FDC0_nhits);
   tree->SetBranchAddress("FDC0_TDC",&FDC0_TDC);
   tree->SetBranchAddress("FDC0_layerid",&FDC0_layerid);
   tree->SetBranchAddress("FDC0_wireid",&FDC0_wireid);
   tree->SetBranchAddress("FDC0_layer_hits",&FDC0_layer_hits);
   tree->SetBranchAddress("FDC0_nlayerx",&FDC0_nlayerx);
   tree->SetBranchAddress("FDC0_nlayery",&FDC0_nlayery);
   tree->SetBranchAddress("FDC0_Track_dl",&FDC0_Track_dl);
   tree->SetBranchAddress("FDC0_Track_XY",&FDC0_Track_XY);
   tree->SetBranchAddress("FDC0_Track_Z",&FDC0_Track_Z);
   tree->SetBranchAddress("FDC0_Track_dXY",&FDC0_Track_dXY);
   tree->SetBranchAddress("FDC0_X",&FDC0_X);
   tree->SetBranchAddress("FDC0_Y",&FDC0_Y);
   tree->SetBranchAddress("FDC0_ThetaX",&FDC0_ThetaX);
   tree->SetBranchAddress("FDC0_ThetaY",&FDC0_ThetaY);
   tree->SetBranchAddress("fdc0Angle",&fdc0Angle);
   tree->SetBranchAddress("fdc0Phi",&fdc0Phi);
   tree->SetBranchAddress("fdc0Position",&fdc0Position);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("vFDC0",&vFDC0);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("dssdQRaw",dssdQRaw);
   tree->SetBranchAddress("dssdTRaw",dssdTRaw);
   tree->SetBranchAddress("csiQRaw",csiQRaw);
   tree->SetBranchAddress("csiQPed",csiQPed);
   tree->SetBranchAddress("RefTime1",&RefTime1);
   tree->SetBranchAddress("RefTime2",&RefTime2);
   tree->SetBranchAddress("dssdQPed",dssdQPed);
   tree->SetBranchAddress("csiQPed",csiQPed);
   tree->SetBranchAddress("dssdQHit",&dssdQHit);
   tree->SetBranchAddress("dssdQHitSide",&dssdQHitSide);
   tree->SetBranchAddress("dssdQHitStripId",&dssdQHitStripId);
   tree->SetBranchAddress("dssdQHitQPed",&dssdQHitQPed);
   tree->SetBranchAddress("dssdTHit",&dssdTHit);
   tree->SetBranchAddress("dssdTHitSide",&dssdTHitSide);
   tree->SetBranchAddress("dssdTHitStripId",&dssdTHitStripId);
   tree->SetBranchAddress("dssdTHitTCal",&dssdTHitTCal);
   tree->SetBranchAddress("dssdHit",&dssdHit);
   tree->SetBranchAddress("dssdHitSide",&dssdHitSide);
   tree->SetBranchAddress("dssdHitFid",&dssdHitFid);
   tree->SetBranchAddress("dssdHitBid",&dssdHitBid);
   tree->SetBranchAddress("dssdHitFQPed",&dssdHitFQPed);
   tree->SetBranchAddress("dssdHitBQPed",&dssdHitBQPed);
   tree->SetBranchAddress("dssdHitTCal",&dssdHitTCal);
   tree->SetBranchAddress("csiQHit",&csiQHit);
   tree->SetBranchAddress("csiQHitId",&csiQHitId);
   tree->SetBranchAddress("csiQHitQPed",&csiQHitQPed);
   tree->SetBranchAddress("csiTHit",&csiTHit);
   tree->SetBranchAddress("csiTHitId",&csiTHitId);
   tree->SetBranchAddress("csiTHitTCal",&csiTHitTCal);
   tree->SetBranchAddress("csiHit",&csiHit);
   tree->SetBranchAddress("csiHitId",&csiHitId);
   tree->SetBranchAddress("csiHitQPed",&csiHitQPed);
   tree->SetBranchAddress("csiHitTCal",&csiHitTCal);
   tree->SetBranchAddress("teleHit",&teleHit);
   tree->SetBranchAddress("teleHitSide",&teleHitSide);
   tree->SetBranchAddress("teleHitFid",&teleHitFid);
   tree->SetBranchAddress("teleHitBid",&teleHitBid);
   tree->SetBranchAddress("teleHitDssdFQPed",&teleHitDssdFQPed);
   tree->SetBranchAddress("teleHitDssdBQPed",&teleHitDssdBQPed);
   tree->SetBranchAddress("teleHitDssdTCal",&teleHitDssdTCal);
   tree->SetBranchAddress("teleHitCid",&teleHitCid);
   tree->SetBranchAddress("teleHitCsiQPed",&teleHitCsiQPed);
   tree->SetBranchAddress("teleHitCsiTCal",&teleHitCsiTCal);
   tree->SetBranchAddress("teleHitDssdFE",&teleHitDssdFE);
   tree->SetBranchAddress("teleHitDssdBE",&teleHitDssdBE);
   tree->SetBranchAddress("teleHitCsiE",&teleHitCsiE);
   tree->SetBranchAddress("bestHit",&bestHit);
   tree->SetBranchAddress("teleCsiE",&teleCsiE);
   tree->SetBranchAddress("teleCsiE_sync",&teleCsiE_sync);
   tree->SetBranchAddress("teleDssdFE",&teleDssdFE);
   tree->SetBranchAddress("teleDssdBE",&teleDssdBE);
   tree->SetBranchAddress("teleDssdFE_old",&teleDssdFE_old);
   tree->SetBranchAddress("teleDssdBE_old",&teleDssdBE_old);
   tree->SetBranchAddress("teleDssdE",&teleDssdE);
   tree->SetBranchAddress("teleDssdMaxE",&teleDssdMaxE);
   tree->SetBranchAddress("teleCsiT",&teleCsiT);
   tree->SetBranchAddress("teleDssdT",&teleDssdT);
   tree->SetBranchAddress("teleEnergy",&teleEnergy);
   tree->SetBranchAddress("telePosition",&telePosition);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("teleAngle",&teleAngle);
   tree->SetBranchAddress("telePhi",&telePhi);
   tree->SetBranchAddress("teleLocusAngle",&teleLocusAngle);
   tree->SetBranchAddress("vTele",&vTele);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("hodNHit",&hodNHit);
   tree->SetBranchAddress("hodID",hodID);
   tree->SetBranchAddress("hodTRaw",hodTRaw);
   tree->SetBranchAddress("hodQRaw",hodQRaw);
   tree->SetBranchAddress("hodQPed",hodQPed);
   tree->SetBranchAddress("hodTCal",hodTCal);
   tree->SetBranchAddress("hodQCal",hodQCal);
   tree->SetBranchAddress("hodBarTCal",hodBarTCal);
   tree->SetBranchAddress("hodBarQCal",hodBarQCal);
   tree->SetBranchAddress("EventNumber",&EventNumber);
   tree->SetBranchAddress("RunNumber",&RunNumber);
   tree->SetBranchAddress("plasTdcRaw0",&plasTdcRaw0);
   tree->SetBranchAddress("plasTdcRaw1",&plasTdcRaw1);
   tree->SetBranchAddress("plasTdcRaw2",&plasTdcRaw2);
   tree->SetBranchAddress("plasTdcRaw3",&plasTdcRaw3);
   tree->SetBranchAddress("rdcTdc",&rdcTdc);
   tree->SetBranchAddress("rdcPlaneId",&rdcPlaneId);
   tree->SetBranchAddress("rdcWireId",&rdcWireId);
   tree->SetBranchAddress("rdcPlaneNHit",&rdcPlaneNHit);
   tree->SetBranchAddress("naiQRaw",naiQRaw);
   tree->SetBranchAddress("plasQRaw",plasQRaw);
   tree->SetBranchAddress("plasTRaw",plasTRaw);
   tree->SetBranchAddress("plasTimeRef",&plasTimeRef);
   tree->SetBranchAddress("rdcX",rdcX);
   tree->SetBranchAddress("rdcY",rdcY);
   tree->SetBranchAddress("rdcA",rdcA);
   tree->SetBranchAddress("rdcB",rdcB);
   tree->SetBranchAddress("rdcChi2",rdcChi2);
   tree->SetBranchAddress("rdcDL",rdcDL);
   tree->SetBranchAddress("rdcTch",rdcTch);
   tree->SetBranchAddress("rdcRes",rdcRes);
   tree->SetBranchAddress("naiQPed",naiQPed);
   tree->SetBranchAddress("plasQPed",plasQPed);
   tree->SetBranchAddress("rdcHit",&rdcHit);
   tree->SetBranchAddress("rdcHitSide",&rdcHitSide);
   tree->SetBranchAddress("naiHit",&naiHit);
   tree->SetBranchAddress("naiHitSide",&naiHitSide);
   tree->SetBranchAddress("naiHitBarId",&naiHitBarId);
   tree->SetBranchAddress("plasHit",&plasHit);
   tree->SetBranchAddress("plasHitSide",&plasHitSide);
   tree->SetBranchAddress("plasTHit",&plasTHit);
   tree->SetBranchAddress("plasQHit",&plasQHit);
   tree->SetBranchAddress("espriHit",&espriHit);
   tree->SetBranchAddress("espriSide",&espriSide);
   tree->SetBranchAddress("espriRdcX",&espriRdcX);
   tree->SetBranchAddress("espriRdcY",&espriRdcY);
   tree->SetBranchAddress("espriPlasQPed",&espriPlasQPed);
   tree->SetBranchAddress("espriNaiBarId",&espriNaiBarId);
   tree->SetBranchAddress("espriNaiQPed",&espriNaiQPed);
   tree->SetBranchAddress("espriPlasT",&espriPlasT);
   tree->SetBranchAddress("espriPlasE_Birks",&espriPlasE_Birks);
   tree->SetBranchAddress("espriPlasE",&espriPlasE);
   tree->SetBranchAddress("espriNaiE",&espriNaiE);
   tree->SetBranchAddress("vESPRI",&vESPRI);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("espriPosition",&espriPosition);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("espriRdcPosition",&espriRdcPosition);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("espriPlasPosition",&espriPlasPosition);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("espriFL",&espriFL);
   tree->SetBranchAddress("espriLocusAngle",&espriLocusAngle);
   tree->SetBranchAddress("espriAngle",&espriAngle);
   tree->SetBranchAddress("espriPhi",&espriPhi);
   tree->SetBranchAddress("beamEnergy",&beamEnergy);
   tree->SetBranchAddress("beamBeta",&beamBeta);
   tree->SetBranchAddress("tofSBTTarget",&tofSBTTarget);
   tree->SetBranchAddress("ppDegraderE",&ppDegraderE);
   tree->SetBranchAddress("ppPlasE",&ppPlasE);
   tree->SetBranchAddress("ppWinE",&ppWinE);
   tree->SetBranchAddress("ppShtE",&ppShtE);
   tree->SetBranchAddress("degraderThickness",&degraderThickness);
   tree->SetBranchAddress("protonEnergy",&protonEnergy);
   tree->SetBranchAddress("apDssdE",&apDssdE);
   tree->SetBranchAddress("apDegraderE",&apDegraderE);
   tree->SetBranchAddress("apWinE",&apWinE);
   tree->SetBranchAddress("alphaEnergy_old",&alphaEnergy_old);
   tree->SetBranchAddress("alphaEnergy",&alphaEnergy);

//     This is the loop skeleton
//       To read only selected branches, Insert statements like:
// tree->SetBranchStatus("*",0);  // disable all branches
// TTreePlayer->SetBranchStatus("branchname",1);  // activate branchname

   Long64_t nentries = tree->GetEntries();

   Long64_t nbytes = 0;
//   for (Long64_t i=0; i<nentries;i++) {
//      nbytes += tree->GetEntry(i);
//   }
}
