{
//////////////////////////////////////////////////////////
//   This file has been automatically generated 
//     (Thu Jan  2 21:27:38 2020 by ROOT version5.34/20)
//   from TTree tree/Analysed Tree:raw,cal,analysed
//   found on file: run0310_analysed.root
//////////////////////////////////////////////////////////


//Reset ROOT and connect tree file
   gROOT->Reset();
   TFile *f = (TFile*)gROOT->GetListOfFiles()->FindObject("run0310_analysed.root");
   if (!f) {
      f = new TFile("run0310_analysed.root");
   }
    f->GetObject("tree",tree);

//Declaration of leaves types
   Int_t           RunNumber;
   Long64_t        EventNumber;
   Int_t           CoincidenceTrigger;
   Int_t           Trig_DSB;
   Int_t           Trig_BxESPRIxTEL;
   Int_t           Trig_BxESPRI;
   Int_t           Trig_BxTEL;
   Int_t           Trig_BxHODP;
   Int_t           Trig_BxHODF;
   Int_t           Trig_BxNEBULA;
   Int_t           F3TRaw[2];
   Int_t           F3QRaw[2];
   Double_t        F3TCal[2];
   Double_t        F3QCal[2];
   Double_t        F3T;
   Double_t        F3Q;
   Int_t           F7TRaw[2];
   Int_t           F7QRaw[2];
   Double_t        F7TCal[2];
   Double_t        F7QCal[2];
   Double_t        F7T;
   Double_t        F7Q;
   Int_t           SBT1TRaw[2];
   Int_t           SBT1QRaw[2];
   Double_t        SBT1TCal[2];
   Double_t        SBT1QCal[2];
   Double_t        SBT1T;
   Double_t        SBT1Q;
   Int_t           SBT2TRaw[2];
   Int_t           SBT2QRaw[2];
   Double_t        SBT2TCal[2];
   Double_t        SBT2QCal[2];
   Double_t        SBT2T;
   Double_t        SBT2Q;
   Double_t        F13T;
   Double_t        F13Q;
   Int_t           SBVTRaw[2];
   Int_t           SBVQRaw[2];
   Double_t        SBVTCal[2];
   Double_t        SBVQCal[2];
   Double_t        SBVT;
   Double_t        SBVQ;
   Double_t        TOF37;
   Double_t        Beta37;
   Double_t        Gamma37;
   Double_t        Ek37;
   Double_t        TOF713;
   Double_t        Beta713;
   Double_t        Gamma713;
   Double_t        Ek713;
   Int_t           BDC1_nhits;
   vector<double>  BDC1_TDC;
   vector<double>  BDC1_layerid;
   vector<double>  BDC1_wireid;
   vector<int>     BDC1_layer_hits;
   Int_t           BDC1_nlayerx;
   Int_t           BDC1_nlayery;
   vector<double>  BDC1_Track_dl;
   vector<double>  BDC1_Track_XY;
   vector<double>  BDC1_Track_Z;
   vector<double>  BDC1_Track_dXY;
   Double_t        BDC1_X;
   Double_t        BDC1_Y;
   Double_t        BDC1_ThetaX;
   Double_t        BDC1_ThetaY;
   Int_t           BDC2_nhits;
   vector<double>  BDC2_TDC;
   vector<double>  BDC2_layerid;
   vector<double>  BDC2_wireid;
   vector<int>     BDC2_layer_hits;
   Int_t           BDC2_nlayerx;
   Int_t           BDC2_nlayery;
   vector<double>  BDC2_Track_dl;
   vector<double>  BDC2_Track_XY;
   vector<double>  BDC2_Track_Z;
   vector<double>  BDC2_Track_dXY;
   Double_t        BDC2_X;
   Double_t        BDC2_Y;
   Double_t        BDC2_ThetaX;
   Double_t        BDC2_ThetaY;
   Double_t        beamFL;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   Int_t           FDC0_nhits;
   vector<double>  FDC0_TDC;
   vector<double>  FDC0_layerid;
   vector<double>  FDC0_wireid;
   vector<int>     FDC0_layer_hits;
   Int_t           FDC0_nlayerx;
   Int_t           FDC0_nlayery;
   vector<double>  FDC0_Track_dl;
   vector<double>  FDC0_Track_XY;
   vector<double>  FDC0_Track_Z;
   vector<double>  FDC0_Track_dXY;
   Double_t        FDC0_X;
   Double_t        FDC0_Y;
   Double_t        FDC0_ThetaX;
   Double_t        FDC0_ThetaY;
   Double_t        resAngle;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   Int_t           dssdQRaw[4][32];
   Int_t           dssdTRaw[4][32];
   Double_t        dssdQScm[4][32];
   Double_t        dssdQCal[4][32];
   Double_t        dssdTCal[4][32];
   Int_t           csiQRaw[7];
   Int_t           csiTRaw[7];
   Double_t        csiQPed[7];
   Double_t        csiQSync[7];
   Double_t        csiQCal[7];
   Double_t        csiTCal[7];
   Int_t           dssdNHit[4];
   Double_t        dssdSideQ[4];
   Int_t           dssdId[4];
   Int_t           csiNHit;
   Int_t           csiHitIdArray[7];
   Int_t           csiId;
   Int_t           dssdFid;
   Int_t           dssdBid;
   Double_t        teleDssdE;
   Double_t        teleCsiE;
   Double_t        teleEnergy;
   Double_t        teleAngle;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   Int_t           hodNHit;
   Int_t           hodID[40];
   Int_t           hodTRaw[2][40];
   Int_t           hodQRaw[2][40];
   Double_t        hodQPed[2][40];
   Double_t        hodTCal[2][40];
   Double_t        hodQCal[2][40];
   Double_t        hodBarTCal[40];
   Double_t        hodBarQCal[40];
   Int_t           rdcHit;
   Int_t           rdcHitSide[2];
   Double_t        rdcHitX[2];
   Double_t        rdcHitY[2];
   Double_t        rdcHitChi2[2];
   Int_t           naiHit;
   Int_t           naiHitSide[7];
   Int_t           naiHitBarId[7];
   Double_t        naiHitQPed[7];
   Int_t           plasHit;
   Int_t           plasHitSide[2];
   Int_t           plasHitQPed[2];
   Double_t        plasTCal[4];
   Int_t           espriHit;
   Int_t           espriHitSide[1];
   Double_t        espriPlasE_singleGain;
   Double_t        espriPlasE_Birks;
   Double_t        espriNaiE_Pol3;
   Double_t        espriPlasE;
   Double_t        espriPlasT;
   Double_t        espriNaiE;
   Double_t        espriDeeEnergy;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   Double_t        espriFL;
   Double_t        espriLocusAngle;
   Double_t        espriEnergy;
   Double_t        espriAngle;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;

   // Set branch addresses.
   tree->SetBranchAddress("RunNumber",&RunNumber);
   tree->SetBranchAddress("EventNumber",&EventNumber);
   tree->SetBranchAddress("CoincidenceTrigger",&CoincidenceTrigger);
   tree->SetBranchAddress("Trig_DSB",&Trig_DSB);
   tree->SetBranchAddress("Trig_BxESPRIxTEL",&Trig_BxESPRIxTEL);
   tree->SetBranchAddress("Trig_BxESPRI",&Trig_BxESPRI);
   tree->SetBranchAddress("Trig_BxTEL",&Trig_BxTEL);
   tree->SetBranchAddress("Trig_BxHODP",&Trig_BxHODP);
   tree->SetBranchAddress("Trig_BxHODF",&Trig_BxHODF);
   tree->SetBranchAddress("Trig_BxNEBULA",&Trig_BxNEBULA);
   tree->SetBranchAddress("F3TRaw",F3TRaw);
   tree->SetBranchAddress("F3QRaw",F3QRaw);
   tree->SetBranchAddress("F3TCal",F3TCal);
   tree->SetBranchAddress("F3QCal",F3QCal);
   tree->SetBranchAddress("F3T",&F3T);
   tree->SetBranchAddress("F3Q",&F3Q);
   tree->SetBranchAddress("F7TRaw",F7TRaw);
   tree->SetBranchAddress("F7QRaw",F7QRaw);
   tree->SetBranchAddress("F7TCal",F7TCal);
   tree->SetBranchAddress("F7QCal",F7QCal);
   tree->SetBranchAddress("F7T",&F7T);
   tree->SetBranchAddress("F7Q",&F7Q);
   tree->SetBranchAddress("SBT1TRaw",SBT1TRaw);
   tree->SetBranchAddress("SBT1QRaw",SBT1QRaw);
   tree->SetBranchAddress("SBT1TCal",SBT1TCal);
   tree->SetBranchAddress("SBT1QCal",SBT1QCal);
   tree->SetBranchAddress("SBT1T",&SBT1T);
   tree->SetBranchAddress("SBT1Q",&SBT1Q);
   tree->SetBranchAddress("SBT2TRaw",SBT2TRaw);
   tree->SetBranchAddress("SBT2QRaw",SBT2QRaw);
   tree->SetBranchAddress("SBT2TCal",SBT2TCal);
   tree->SetBranchAddress("SBT2QCal",SBT2QCal);
   tree->SetBranchAddress("SBT2T",&SBT2T);
   tree->SetBranchAddress("SBT2Q",&SBT2Q);
   tree->SetBranchAddress("F13T",&F13T);
   tree->SetBranchAddress("F13Q",&F13Q);
   tree->SetBranchAddress("SBVTRaw",SBVTRaw);
   tree->SetBranchAddress("SBVQRaw",SBVQRaw);
   tree->SetBranchAddress("SBVTCal",SBVTCal);
   tree->SetBranchAddress("SBVQCal",SBVQCal);
   tree->SetBranchAddress("SBVT",&SBVT);
   tree->SetBranchAddress("SBVQ",&SBVQ);
   tree->SetBranchAddress("TOF37",&TOF37);
   tree->SetBranchAddress("Beta37",&Beta37);
   tree->SetBranchAddress("Gamma37",&Gamma37);
   tree->SetBranchAddress("Ek37",&Ek37);
   tree->SetBranchAddress("TOF713",&TOF713);
   tree->SetBranchAddress("Beta713",&Beta713);
   tree->SetBranchAddress("Gamma713",&Gamma713);
   tree->SetBranchAddress("Ek713",&Ek713);
   tree->SetBranchAddress("BDC1_nhits",&BDC1_nhits);
   tree->SetBranchAddress("BDC1_TDC",&BDC1_TDC);
   tree->SetBranchAddress("BDC1_layerid",&BDC1_layerid);
   tree->SetBranchAddress("BDC1_wireid",&BDC1_wireid);
   tree->SetBranchAddress("BDC1_layer_hits",&BDC1_layer_hits);
   tree->SetBranchAddress("BDC1_nlayerx",&BDC1_nlayerx);
   tree->SetBranchAddress("BDC1_nlayery",&BDC1_nlayery);
   tree->SetBranchAddress("BDC1_Track_dl",&BDC1_Track_dl);
   tree->SetBranchAddress("BDC1_Track_XY",&BDC1_Track_XY);
   tree->SetBranchAddress("BDC1_Track_Z",&BDC1_Track_Z);
   tree->SetBranchAddress("BDC1_Track_dXY",&BDC1_Track_dXY);
   tree->SetBranchAddress("BDC1_X",&BDC1_X);
   tree->SetBranchAddress("BDC1_Y",&BDC1_Y);
   tree->SetBranchAddress("BDC1_ThetaX",&BDC1_ThetaX);
   tree->SetBranchAddress("BDC1_ThetaY",&BDC1_ThetaY);
   tree->SetBranchAddress("BDC2_nhits",&BDC2_nhits);
   tree->SetBranchAddress("BDC2_TDC",&BDC2_TDC);
   tree->SetBranchAddress("BDC2_layerid",&BDC2_layerid);
   tree->SetBranchAddress("BDC2_wireid",&BDC2_wireid);
   tree->SetBranchAddress("BDC2_layer_hits",&BDC2_layer_hits);
   tree->SetBranchAddress("BDC2_nlayerx",&BDC2_nlayerx);
   tree->SetBranchAddress("BDC2_nlayery",&BDC2_nlayery);
   tree->SetBranchAddress("BDC2_Track_dl",&BDC2_Track_dl);
   tree->SetBranchAddress("BDC2_Track_XY",&BDC2_Track_XY);
   tree->SetBranchAddress("BDC2_Track_Z",&BDC2_Track_Z);
   tree->SetBranchAddress("BDC2_Track_dXY",&BDC2_Track_dXY);
   tree->SetBranchAddress("BDC2_X",&BDC2_X);
   tree->SetBranchAddress("BDC2_Y",&BDC2_Y);
   tree->SetBranchAddress("BDC2_ThetaX",&BDC2_ThetaX);
   tree->SetBranchAddress("BDC2_ThetaY",&BDC2_ThetaY);
   tree->SetBranchAddress("beamFL",&beamFL);
   tree->SetBranchAddress("vBeam",&vBeam);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("vBDC1",&vBDC1);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("vBDC2",&vBDC2);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("vTarget",&vTarget);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("vSBT",&vSBT);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("FDC0_nhits",&FDC0_nhits);
   tree->SetBranchAddress("FDC0_TDC",&FDC0_TDC);
   tree->SetBranchAddress("FDC0_layerid",&FDC0_layerid);
   tree->SetBranchAddress("FDC0_wireid",&FDC0_wireid);
   tree->SetBranchAddress("FDC0_layer_hits",&FDC0_layer_hits);
   tree->SetBranchAddress("FDC0_nlayerx",&FDC0_nlayerx);
   tree->SetBranchAddress("FDC0_nlayery",&FDC0_nlayery);
   tree->SetBranchAddress("FDC0_Track_dl",&FDC0_Track_dl);
   tree->SetBranchAddress("FDC0_Track_XY",&FDC0_Track_XY);
   tree->SetBranchAddress("FDC0_Track_Z",&FDC0_Track_Z);
   tree->SetBranchAddress("FDC0_Track_dXY",&FDC0_Track_dXY);
   tree->SetBranchAddress("FDC0_X",&FDC0_X);
   tree->SetBranchAddress("FDC0_Y",&FDC0_Y);
   tree->SetBranchAddress("FDC0_ThetaX",&FDC0_ThetaX);
   tree->SetBranchAddress("FDC0_ThetaY",&FDC0_ThetaY);
   tree->SetBranchAddress("resAngle",&resAngle);
   tree->SetBranchAddress("fdc0Position",&fdc0Position);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("vFDC0",&vFDC0);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("dssdQRaw",dssdQRaw);
   tree->SetBranchAddress("dssdTRaw",dssdTRaw);
   tree->SetBranchAddress("dssdQScm",dssdQScm);
   tree->SetBranchAddress("dssdQCal",dssdQCal);
   tree->SetBranchAddress("dssdTCal",dssdTCal);
   tree->SetBranchAddress("csiQRaw",csiQRaw);
   tree->SetBranchAddress("csiTRaw",csiTRaw);
   tree->SetBranchAddress("csiQPed",csiQPed);
   tree->SetBranchAddress("csiQSync",csiQSync);
   tree->SetBranchAddress("csiQCal",csiQCal);
   tree->SetBranchAddress("csiTCal",csiTCal);
   tree->SetBranchAddress("dssdNHit",dssdNHit);
   tree->SetBranchAddress("dssdSideQ",dssdSideQ);
   tree->SetBranchAddress("dssdId",dssdId);
   tree->SetBranchAddress("csiNHit",&csiNHit);
   tree->SetBranchAddress("csiHitIdArray",csiHitIdArray);
   tree->SetBranchAddress("csiId",&csiId);
   tree->SetBranchAddress("dssdFid",&dssdFid);
   tree->SetBranchAddress("dssdBid",&dssdBid);
   tree->SetBranchAddress("teleDssdE",&teleDssdE);
   tree->SetBranchAddress("teleCsiE",&teleCsiE);
   tree->SetBranchAddress("teleEnergy",&teleEnergy);
   tree->SetBranchAddress("teleAngle",&teleAngle);
   tree->SetBranchAddress("telePosition",&telePosition);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("hodNHit",&hodNHit);
   tree->SetBranchAddress("hodID",hodID);
   tree->SetBranchAddress("hodTRaw",hodTRaw);
   tree->SetBranchAddress("hodQRaw",hodQRaw);
   tree->SetBranchAddress("hodQPed",hodQPed);
   tree->SetBranchAddress("hodTCal",hodTCal);
   tree->SetBranchAddress("hodQCal",hodQCal);
   tree->SetBranchAddress("hodBarTCal",hodBarTCal);
   tree->SetBranchAddress("hodBarQCal",hodBarQCal);
   tree->SetBranchAddress("rdcHit",&rdcHit);
   tree->SetBranchAddress("rdcHitSide",rdcHitSide);
   tree->SetBranchAddress("rdcHitX",rdcHitX);
   tree->SetBranchAddress("rdcHitY",rdcHitY);
   tree->SetBranchAddress("rdcHitChi2",rdcHitChi2);
   tree->SetBranchAddress("naiHit",&naiHit);
   tree->SetBranchAddress("naiHitSide",naiHitSide);
   tree->SetBranchAddress("naiHitBarId",naiHitBarId);
   tree->SetBranchAddress("naiHitQPed",naiHitQPed);
   tree->SetBranchAddress("plasHit",&plasHit);
   tree->SetBranchAddress("plasHitSide",plasHitSide);
   tree->SetBranchAddress("plasHitQPed",plasHitQPed);
   tree->SetBranchAddress("plasTCal",plasTCal);
   tree->SetBranchAddress("espriHit",&espriHit);
   tree->SetBranchAddress("espriHitSide",espriHitSide);
   tree->SetBranchAddress("espriPlasE_singleGain",&espriPlasE_singleGain);
   tree->SetBranchAddress("espriPlasE_Birks",&espriPlasE_Birks);
   tree->SetBranchAddress("espriNaiE_Pol3",&espriNaiE_Pol3);
   tree->SetBranchAddress("espriPlasE",&espriPlasE);
   tree->SetBranchAddress("espriPlasT",&espriPlasT);
   tree->SetBranchAddress("espriNaiE",&espriNaiE);
   tree->SetBranchAddress("espriDeeEnergy",&espriDeeEnergy);
   tree->SetBranchAddress("vESPRI",&vESPRI);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("espriRdcPosition",&espriRdcPosition);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("espriPlasPosition",&espriPlasPosition);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("espriFL",&espriFL);
   tree->SetBranchAddress("espriLocusAngle",&espriLocusAngle);
   tree->SetBranchAddress("espriEnergy",&espriEnergy);
   tree->SetBranchAddress("espriAngle",&espriAngle);
   tree->SetBranchAddress("espriPosition",&espriPosition);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);

//     This is the loop skeleton
//       To read only selected branches, Insert statements like:
// tree->SetBranchStatus("*",0);  // disable all branches
// TTreePlayer->SetBranchStatus("branchname",1);  // activate branchname

   Long64_t nentries = tree->GetEntries();

   Long64_t nbytes = 0;
//   for (Long64_t i=0; i<nentries;i++) {
//      nbytes += tree->GetEntry(i);
//   }
}
