{
//////////////////////////////////////////////////////////
//   This file has been automatically generated 
//     (Mon Apr  8 20:43:37 2019 by ROOT version5.34/20)
//   from TTree tree/Analysed Tree:raw,cal,analysed
//   found on file: run0595_analysed.root_
//////////////////////////////////////////////////////////


//Reset ROOT and connect tree file
   gROOT->Reset();
   TFile *f = (TFile*)gROOT->GetListOfFiles()->FindObject("run0595_analysed.root_");
   if (!f) {
      f = new TFile("run0595_analysed.root_");
   }
    f->GetObject("tree",tree);

//Declaration of leaves types
   Int_t           RunNumber;
   Long64_t        EventNumber;
   Int_t           CoincidenceTrigger;
   Int_t           Trig_DSB;
   Int_t           Trig_BxESPRIxTEL;
   Int_t           Trig_BxESPRI;
   Int_t           Trig_BxTEL;
   Int_t           Trig_BxHODP;
   Int_t           Trig_BxHODF;
   Int_t           Trig_BxNEBULA;
   Double_t        F3_LTRaw;
   Double_t        F3_RTRaw;
   Double_t        F3_LTSlew;
   Double_t        F3_RTSlew;
   Double_t        F3_LQRaw;
   Double_t        F3_RQRaw;
   Double_t        F7_LTRaw;
   Double_t        F7_RTRaw;
   Double_t        F7_LTSlew;
   Double_t        F7_RTSlew;
   Double_t        F7_LQRaw;
   Double_t        F7_RQRaw;
   Double_t        SBT1_LTRaw;
   Double_t        SBT1_RTRaw;
   Double_t        SBT1_LTSlew;
   Double_t        SBT1_RTSlew;
   Double_t        SBT1_LQRaw;
   Double_t        SBT1_RQRaw;
   Double_t        SBT2_LTRaw;
   Double_t        SBT2_RTRaw;
   Double_t        SBT2_LTSlew;
   Double_t        SBT2_RTSlew;
   Double_t        SBT2_LQRaw;
   Double_t        SBT2_RQRaw;
   Double_t        SBV_RQRaw;
   Double_t        SBV_RTRaw;
   Double_t        SBV_RTSlew;
   Double_t        F3_Charge;
   Double_t        F3_Time;
   Double_t        F7_Charge;
   Double_t        F7_Time;
   Double_t        F13_Charge;
   Double_t        F13_Time;
   Double_t        SBV_Charge;
   Double_t        SBV_Time;
   Double_t        SBT1_Charge;
   Double_t        SBT1_Time;
   Double_t        SBT2_Charge;
   Double_t        SBT2_Time;
   Double_t        TOF37;
   Double_t        Beta37;
   Double_t        Gamma37;
   Double_t        Ek37;
   Double_t        TOF713;
   Double_t        Beta713;
   Double_t        Gamma713;
   Double_t        Ek713;
   Int_t           BDC1_nhits;
   vector<double>  BDC1_TDC;
   vector<double>  BDC1_layerid;
   vector<double>  BDC1_wireid;
   vector<int>     BDC1_layer_hits;
   Int_t           BDC1_nlayerx;
   Int_t           BDC1_nlayery;
   vector<double>  BDC1_Track_dl;
   vector<double>  BDC1_Track_XY;
   vector<double>  BDC1_Track_Z;
   vector<double>  BDC1_Track_dXY;
   Double_t        BDC1_X;
   Double_t        BDC1_Y;
   Double_t        BDC1_ThetaX;
   Double_t        BDC1_ThetaY;
   Int_t           BDC2_nhits;
   vector<double>  BDC2_TDC;
   vector<double>  BDC2_layerid;
   vector<double>  BDC2_wireid;
   vector<int>     BDC2_layer_hits;
   Int_t           BDC2_nlayerx;
   Int_t           BDC2_nlayery;
   vector<double>  BDC2_Track_dl;
   vector<double>  BDC2_Track_XY;
   vector<double>  BDC2_Track_Z;
   vector<double>  BDC2_Track_dXY;
   Double_t        BDC2_X;
   Double_t        BDC2_Y;
   Double_t        BDC2_ThetaX;
   Double_t        BDC2_ThetaY;
   Double_t        Target_X;
   Double_t        Target_Y;
   Double_t        Target_ThetaX;
   Double_t        Target_ThetaY;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   UInt_t          fUniqueID;
   UInt_t          fBits;
   Double_t        fX;
   Double_t        fY;
   Double_t        fZ;
   Int_t           FDC0_nhits;
   vector<double>  FDC0_TDC;
   vector<double>  FDC0_layerid;
   vector<double>  FDC0_wireid;
   vector<int>     FDC0_layer_hits;
   Int_t           FDC0_nlayerx;
   Int_t           FDC0_nlayery;
   vector<double>  FDC0_Track_dl;
   vector<double>  FDC0_Track_XY;
   vector<double>  FDC0_Track_Z;
   vector<double>  FDC0_Track_dXY;
   Double_t        FDC0_X;
   Double_t        FDC0_Y;
   Double_t        FDC0_ThetaX;
   Double_t        FDC0_ThetaY;
   Int_t           dssdEnergyRaw[4][32];
   Int_t           dssdTimeRaw[4][32];
   Double_t        dssdEnergyCal[4][32];
   Double_t        dssdTimeCal[4][32];
   Int_t           csiEnergyRaw;
   Int_t           csiTimeRaw;
   Double_t        csiEnergyCal;
   Double_t        csiTimeCal;
   Int_t           multiplicity[4];

   // Set branch addresses.
   tree->SetBranchAddress("RunNumber",&RunNumber);
   tree->SetBranchAddress("EventNumber",&EventNumber);
   tree->SetBranchAddress("CoincidenceTrigger",&CoincidenceTrigger);
   tree->SetBranchAddress("Trig_DSB",&Trig_DSB);
   tree->SetBranchAddress("Trig_BxESPRIxTEL",&Trig_BxESPRIxTEL);
   tree->SetBranchAddress("Trig_BxESPRI",&Trig_BxESPRI);
   tree->SetBranchAddress("Trig_BxTEL",&Trig_BxTEL);
   tree->SetBranchAddress("Trig_BxHODP",&Trig_BxHODP);
   tree->SetBranchAddress("Trig_BxHODF",&Trig_BxHODF);
   tree->SetBranchAddress("Trig_BxNEBULA",&Trig_BxNEBULA);
   tree->SetBranchAddress("F3_LTRaw",&F3_LTRaw);
   tree->SetBranchAddress("F3_RTRaw",&F3_RTRaw);
   tree->SetBranchAddress("F3_LTSlew",&F3_LTSlew);
   tree->SetBranchAddress("F3_RTSlew",&F3_RTSlew);
   tree->SetBranchAddress("F3_LQRaw",&F3_LQRaw);
   tree->SetBranchAddress("F3_RQRaw",&F3_RQRaw);
   tree->SetBranchAddress("F7_LTRaw",&F7_LTRaw);
   tree->SetBranchAddress("F7_RTRaw",&F7_RTRaw);
   tree->SetBranchAddress("F7_LTSlew",&F7_LTSlew);
   tree->SetBranchAddress("F7_RTSlew",&F7_RTSlew);
   tree->SetBranchAddress("F7_LQRaw",&F7_LQRaw);
   tree->SetBranchAddress("F7_RQRaw",&F7_RQRaw);
   tree->SetBranchAddress("SBT1_LTRaw",&SBT1_LTRaw);
   tree->SetBranchAddress("SBT1_RTRaw",&SBT1_RTRaw);
   tree->SetBranchAddress("SBT1_LTSlew",&SBT1_LTSlew);
   tree->SetBranchAddress("SBT1_RTSlew",&SBT1_RTSlew);
   tree->SetBranchAddress("SBT1_LQRaw",&SBT1_LQRaw);
   tree->SetBranchAddress("SBT1_RQRaw",&SBT1_RQRaw);
   tree->SetBranchAddress("SBT2_LTRaw",&SBT2_LTRaw);
   tree->SetBranchAddress("SBT2_RTRaw",&SBT2_RTRaw);
   tree->SetBranchAddress("SBT2_LTSlew",&SBT2_LTSlew);
   tree->SetBranchAddress("SBT2_RTSlew",&SBT2_RTSlew);
   tree->SetBranchAddress("SBT2_LQRaw",&SBT2_LQRaw);
   tree->SetBranchAddress("SBT2_RQRaw",&SBT2_RQRaw);
   tree->SetBranchAddress("SBV_RQRaw",&SBV_RQRaw);
   tree->SetBranchAddress("SBV_RTRaw",&SBV_RTRaw);
   tree->SetBranchAddress("SBV_RTSlew",&SBV_RTSlew);
   tree->SetBranchAddress("F3_Charge",&F3_Charge);
   tree->SetBranchAddress("F3_Time",&F3_Time);
   tree->SetBranchAddress("F7_Charge",&F7_Charge);
   tree->SetBranchAddress("F7_Time",&F7_Time);
   tree->SetBranchAddress("F13_Charge",&F13_Charge);
   tree->SetBranchAddress("F13_Time",&F13_Time);
   tree->SetBranchAddress("SBV_Charge",&SBV_Charge);
   tree->SetBranchAddress("SBV_Time",&SBV_Time);
   tree->SetBranchAddress("SBT1_Charge",&SBT1_Charge);
   tree->SetBranchAddress("SBT1_Time",&SBT1_Time);
   tree->SetBranchAddress("SBT2_Charge",&SBT2_Charge);
   tree->SetBranchAddress("SBT2_Time",&SBT2_Time);
   tree->SetBranchAddress("TOF37",&TOF37);
   tree->SetBranchAddress("Beta37",&Beta37);
   tree->SetBranchAddress("Gamma37",&Gamma37);
   tree->SetBranchAddress("Ek37",&Ek37);
   tree->SetBranchAddress("TOF713",&TOF713);
   tree->SetBranchAddress("Beta713",&Beta713);
   tree->SetBranchAddress("Gamma713",&Gamma713);
   tree->SetBranchAddress("Ek713",&Ek713);
   tree->SetBranchAddress("BDC1_nhits",&BDC1_nhits);
   tree->SetBranchAddress("BDC1_TDC",&BDC1_TDC);
   tree->SetBranchAddress("BDC1_layerid",&BDC1_layerid);
   tree->SetBranchAddress("BDC1_wireid",&BDC1_wireid);
   tree->SetBranchAddress("BDC1_layer_hits",&BDC1_layer_hits);
   tree->SetBranchAddress("BDC1_nlayerx",&BDC1_nlayerx);
   tree->SetBranchAddress("BDC1_nlayery",&BDC1_nlayery);
   tree->SetBranchAddress("BDC1_Track_dl",&BDC1_Track_dl);
   tree->SetBranchAddress("BDC1_Track_XY",&BDC1_Track_XY);
   tree->SetBranchAddress("BDC1_Track_Z",&BDC1_Track_Z);
   tree->SetBranchAddress("BDC1_Track_dXY",&BDC1_Track_dXY);
   tree->SetBranchAddress("BDC1_X",&BDC1_X);
   tree->SetBranchAddress("BDC1_Y",&BDC1_Y);
   tree->SetBranchAddress("BDC1_ThetaX",&BDC1_ThetaX);
   tree->SetBranchAddress("BDC1_ThetaY",&BDC1_ThetaY);
   tree->SetBranchAddress("BDC2_nhits",&BDC2_nhits);
   tree->SetBranchAddress("BDC2_TDC",&BDC2_TDC);
   tree->SetBranchAddress("BDC2_layerid",&BDC2_layerid);
   tree->SetBranchAddress("BDC2_wireid",&BDC2_wireid);
   tree->SetBranchAddress("BDC2_layer_hits",&BDC2_layer_hits);
   tree->SetBranchAddress("BDC2_nlayerx",&BDC2_nlayerx);
   tree->SetBranchAddress("BDC2_nlayery",&BDC2_nlayery);
   tree->SetBranchAddress("BDC2_Track_dl",&BDC2_Track_dl);
   tree->SetBranchAddress("BDC2_Track_XY",&BDC2_Track_XY);
   tree->SetBranchAddress("BDC2_Track_Z",&BDC2_Track_Z);
   tree->SetBranchAddress("BDC2_Track_dXY",&BDC2_Track_dXY);
   tree->SetBranchAddress("BDC2_X",&BDC2_X);
   tree->SetBranchAddress("BDC2_Y",&BDC2_Y);
   tree->SetBranchAddress("BDC2_ThetaX",&BDC2_ThetaX);
   tree->SetBranchAddress("BDC2_ThetaY",&BDC2_ThetaY);
   tree->SetBranchAddress("Target_X",&Target_X);
   tree->SetBranchAddress("Target_Y",&Target_Y);
   tree->SetBranchAddress("Target_ThetaX",&Target_ThetaX);
   tree->SetBranchAddress("Target_ThetaY",&Target_ThetaY);
   tree->SetBranchAddress("vBeam",&vBeam);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("vBDC1",&vBDC1);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("vBDC2",&vBDC2);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("vTarget",&vTarget);
   tree->SetBranchAddress("fUniqueID",&fUniqueID);
   tree->SetBranchAddress("fBits",&fBits);
   tree->SetBranchAddress("fX",&fX);
   tree->SetBranchAddress("fY",&fY);
   tree->SetBranchAddress("fZ",&fZ);
   tree->SetBranchAddress("FDC0_nhits",&FDC0_nhits);
   tree->SetBranchAddress("FDC0_TDC",&FDC0_TDC);
   tree->SetBranchAddress("FDC0_layerid",&FDC0_layerid);
   tree->SetBranchAddress("FDC0_wireid",&FDC0_wireid);
   tree->SetBranchAddress("FDC0_layer_hits",&FDC0_layer_hits);
   tree->SetBranchAddress("FDC0_nlayerx",&FDC0_nlayerx);
   tree->SetBranchAddress("FDC0_nlayery",&FDC0_nlayery);
   tree->SetBranchAddress("FDC0_Track_dl",&FDC0_Track_dl);
   tree->SetBranchAddress("FDC0_Track_XY",&FDC0_Track_XY);
   tree->SetBranchAddress("FDC0_Track_Z",&FDC0_Track_Z);
   tree->SetBranchAddress("FDC0_Track_dXY",&FDC0_Track_dXY);
   tree->SetBranchAddress("FDC0_X",&FDC0_X);
   tree->SetBranchAddress("FDC0_Y",&FDC0_Y);
   tree->SetBranchAddress("FDC0_ThetaX",&FDC0_ThetaX);
   tree->SetBranchAddress("FDC0_ThetaY",&FDC0_ThetaY);
   tree->SetBranchAddress("dssdEnergyRaw",dssdEnergyRaw);
   tree->SetBranchAddress("dssdTimeRaw",dssdTimeRaw);
   tree->SetBranchAddress("dssdEnergyCal",dssdEnergyCal);
   tree->SetBranchAddress("dssdTimeCal",dssdTimeCal);
   tree->SetBranchAddress("csiEnergyRaw",&csiEnergyRaw);
   tree->SetBranchAddress("csiTimeRaw",&csiTimeRaw);
   tree->SetBranchAddress("csiEnergyCal",&csiEnergyCal);
   tree->SetBranchAddress("csiTimeCal",&csiTimeCal);
   tree->SetBranchAddress("multiplicity",multiplicity);

//     This is the loop skeleton
//       To read only selected branches, Insert statements like:
// tree->SetBranchStatus("*",0);  // disable all branches
// TTreePlayer->SetBranchStatus("branchname",1);  // activate branchname

   Long64_t nentries = tree->GetEntries();

   Long64_t nbytes = 0;
//   for (Long64_t i=0; i<nentries;i++) {
//      nbytes += tree->GetEntry(i);
//   }
}
