class MergeHOD:public Convert{
	private:
	public:
		//Declaration of leaves types
		Double_t        Hodo1_Charge;
		Double_t        Hodo1_Charge_C;
		Double_t        Hodo1_ChargeU;
		Double_t        Hodo1_ChargeD;
		Double_t        Hodo1_Time;
		Double_t        Hodo1_Time_C;
		Double_t        Hodo1_ChargeCalU;
		Double_t        Hodo1_ChargeCalD;
		Double_t        Hodo1_TimeSlwU;
		Double_t        Hodo1_TimeSlwD;
		Double_t        Hodo1_TimeRawU;
		Double_t        Hodo1_TimeRawD;
		Double_t        Hodo2_Charge;
		Double_t        Hodo2_Charge_C;
		Double_t        Hodo2_ChargeU;
		Double_t        Hodo2_ChargeD;
		Double_t        Hodo2_Time;
		Double_t        Hodo2_Time_C;
		Double_t        Hodo2_ChargeCalU;
		Double_t        Hodo2_ChargeCalD;
		Double_t        Hodo2_TimeSlwU;
		Double_t        Hodo2_TimeSlwD;
		Double_t        Hodo2_TimeRawU;
		Double_t        Hodo2_TimeRawD;
		Double_t        Hodo3_Charge;
		Double_t        Hodo3_Charge_C;
		Double_t        Hodo3_ChargeU;
		Double_t        Hodo3_ChargeD;
		Double_t        Hodo3_Time;
		Double_t        Hodo3_Time_C;
		Double_t        Hodo3_ChargeCalU;
		Double_t        Hodo3_ChargeCalD;
		Double_t        Hodo3_TimeSlwU;
		Double_t        Hodo3_TimeSlwD;
		Double_t        Hodo3_TimeRawU;
		Double_t        Hodo3_TimeRawD;
		Double_t        Hodo4_Charge;
		Double_t        Hodo4_Charge_C;
		Double_t        Hodo4_ChargeU;
		Double_t        Hodo4_ChargeD;
		Double_t        Hodo4_Time;
		Double_t        Hodo4_Time_C;
		Double_t        Hodo4_ChargeCalU;
		Double_t        Hodo4_ChargeCalD;
		Double_t        Hodo4_TimeSlwU;
		Double_t        Hodo4_TimeSlwD;
		Double_t        Hodo4_TimeRawU;
		Double_t        Hodo4_TimeRawD;
		Double_t        Hodo5_Charge;
		Double_t        Hodo5_Charge_C;
		Double_t        Hodo5_ChargeU;
		Double_t        Hodo5_ChargeD;
		Double_t        Hodo5_Time;
		Double_t        Hodo5_Time_C;
		Double_t        Hodo5_ChargeCalU;
		Double_t        Hodo5_ChargeCalD;
		Double_t        Hodo5_TimeSlwU;
		Double_t        Hodo5_TimeSlwD;
		Double_t        Hodo5_TimeRawU;
		Double_t        Hodo5_TimeRawD;
		Double_t        Hodo6_Charge;
		Double_t        Hodo6_Charge_C;
		Double_t        Hodo6_ChargeU;
		Double_t        Hodo6_ChargeD;
		Double_t        Hodo6_Time;
		Double_t        Hodo6_Time_C;
		Double_t        Hodo6_ChargeCalU;
		Double_t        Hodo6_ChargeCalD;
		Double_t        Hodo6_TimeSlwU;
		Double_t        Hodo6_TimeSlwD;
		Double_t        Hodo6_TimeRawU;
		Double_t        Hodo6_TimeRawD;
		Double_t        Hodo7_Charge;
		Double_t        Hodo7_Charge_C;
		Double_t        Hodo7_ChargeU;
		Double_t        Hodo7_ChargeD;
		Double_t        Hodo7_Time;
		Double_t        Hodo7_Time_C;
		Double_t        Hodo7_ChargeCalU;
		Double_t        Hodo7_ChargeCalD;
		Double_t        Hodo7_TimeSlwU;
		Double_t        Hodo7_TimeSlwD;
		Double_t        Hodo7_TimeRawU;
		Double_t        Hodo7_TimeRawD;
		Double_t        Hodo8_Charge;
		Double_t        Hodo8_Charge_C;
		Double_t        Hodo8_ChargeU;
		Double_t        Hodo8_ChargeD;
		Double_t        Hodo8_Time;
		Double_t        Hodo8_Time_C;
		Double_t        Hodo8_ChargeCalU;
		Double_t        Hodo8_ChargeCalD;
		Double_t        Hodo8_TimeSlwU;
		Double_t        Hodo8_TimeSlwD;
		Double_t        Hodo8_TimeRawU;
		Double_t        Hodo8_TimeRawD;
		Double_t        Hodo9_Charge;
		Double_t        Hodo9_Charge_C;
		Double_t        Hodo9_ChargeU;
		Double_t        Hodo9_ChargeD;
		Double_t        Hodo9_Time;
		Double_t        Hodo9_Time_C;
		Double_t        Hodo9_ChargeCalU;
		Double_t        Hodo9_ChargeCalD;
		Double_t        Hodo9_TimeSlwU;
		Double_t        Hodo9_TimeSlwD;
		Double_t        Hodo9_TimeRawU;
		Double_t        Hodo9_TimeRawD;
		Double_t        Hodo10_Charge;
		Double_t        Hodo10_Charge_C;
		Double_t        Hodo10_ChargeU;
		Double_t        Hodo10_ChargeD;
		Double_t        Hodo10_Time;
		Double_t        Hodo10_Time_C;
		Double_t        Hodo10_ChargeCalU;
		Double_t        Hodo10_ChargeCalD;
		Double_t        Hodo10_TimeSlwU;
		Double_t        Hodo10_TimeSlwD;
		Double_t        Hodo10_TimeRawU;
		Double_t        Hodo10_TimeRawD;
		Double_t        Hodo11_Charge;
		Double_t        Hodo11_Charge_C;
		Double_t        Hodo11_ChargeU;
		Double_t        Hodo11_ChargeD;
		Double_t        Hodo11_Time;
		Double_t        Hodo11_Time_C;
		Double_t        Hodo11_ChargeCalU;
		Double_t        Hodo11_ChargeCalD;
		Double_t        Hodo11_TimeSlwU;
		Double_t        Hodo11_TimeSlwD;
		Double_t        Hodo11_TimeRawU;
		Double_t        Hodo11_TimeRawD;
		Double_t        Hodo12_Charge;
		Double_t        Hodo12_Charge_C;
		Double_t        Hodo12_ChargeU;
		Double_t        Hodo12_ChargeD;
		Double_t        Hodo12_Time;
		Double_t        Hodo12_Time_C;
		Double_t        Hodo12_ChargeCalU;
		Double_t        Hodo12_ChargeCalD;
		Double_t        Hodo12_TimeSlwU;
		Double_t        Hodo12_TimeSlwD;
		Double_t        Hodo12_TimeRawU;
		Double_t        Hodo12_TimeRawD;
		Double_t        Hodo13_Charge;
		Double_t        Hodo13_Charge_C;
		Double_t        Hodo13_ChargeU;
		Double_t        Hodo13_ChargeD;
		Double_t        Hodo13_Time;
		Double_t        Hodo13_Time_C;
		Double_t        Hodo13_ChargeCalU;
		Double_t        Hodo13_ChargeCalD;
		Double_t        Hodo13_TimeSlwU;
		Double_t        Hodo13_TimeSlwD;
		Double_t        Hodo13_TimeRawU;
		Double_t        Hodo13_TimeRawD;
		Double_t        Hodo14_Charge;
		Double_t        Hodo14_Charge_C;
		Double_t        Hodo14_ChargeU;
		Double_t        Hodo14_ChargeD;
		Double_t        Hodo14_Time;
		Double_t        Hodo14_Time_C;
		Double_t        Hodo14_ChargeCalU;
		Double_t        Hodo14_ChargeCalD;
		Double_t        Hodo14_TimeSlwU;
		Double_t        Hodo14_TimeSlwD;
		Double_t        Hodo14_TimeRawU;
		Double_t        Hodo14_TimeRawD;
		Double_t        Hodo15_Charge;
		Double_t        Hodo15_Charge_C;
		Double_t        Hodo15_ChargeU;
		Double_t        Hodo15_ChargeD;
		Double_t        Hodo15_Time;
		Double_t        Hodo15_Time_C;
		Double_t        Hodo15_ChargeCalU;
		Double_t        Hodo15_ChargeCalD;
		Double_t        Hodo15_TimeSlwU;
		Double_t        Hodo15_TimeSlwD;
		Double_t        Hodo15_TimeRawU;
		Double_t        Hodo15_TimeRawD;
		Double_t        Hodo16_Charge;
		Double_t        Hodo16_Charge_C;
		Double_t        Hodo16_ChargeU;
		Double_t        Hodo16_ChargeD;
		Double_t        Hodo16_Time;
		Double_t        Hodo16_Time_C;
		Double_t        Hodo16_ChargeCalU;
		Double_t        Hodo16_ChargeCalD;
		Double_t        Hodo16_TimeSlwU;
		Double_t        Hodo16_TimeSlwD;
		Double_t        Hodo16_TimeRawU;
		Double_t        Hodo16_TimeRawD;
		Double_t        Hodo17_Charge;
		Double_t        Hodo17_Charge_C;
		Double_t        Hodo17_ChargeU;
		Double_t        Hodo17_ChargeD;
		Double_t        Hodo17_Time;
		Double_t        Hodo17_Time_C;
		Double_t        Hodo17_ChargeCalU;
		Double_t        Hodo17_ChargeCalD;
		Double_t        Hodo17_TimeSlwU;
		Double_t        Hodo17_TimeSlwD;
		Double_t        Hodo17_TimeRawU;
		Double_t        Hodo17_TimeRawD;
		Double_t        Hodo18_Charge;
		Double_t        Hodo18_Charge_C;
		Double_t        Hodo18_ChargeU;
		Double_t        Hodo18_ChargeD;
		Double_t        Hodo18_Time;
		Double_t        Hodo18_Time_C;
		Double_t        Hodo18_ChargeCalU;
		Double_t        Hodo18_ChargeCalD;
		Double_t        Hodo18_TimeSlwU;
		Double_t        Hodo18_TimeSlwD;
		Double_t        Hodo18_TimeRawU;
		Double_t        Hodo18_TimeRawD;
		Double_t        Hodo19_Charge;
		Double_t        Hodo19_Charge_C;
		Double_t        Hodo19_ChargeU;
		Double_t        Hodo19_ChargeD;
		Double_t        Hodo19_Time;
		Double_t        Hodo19_Time_C;
		Double_t        Hodo19_ChargeCalU;
		Double_t        Hodo19_ChargeCalD;
		Double_t        Hodo19_TimeSlwU;
		Double_t        Hodo19_TimeSlwD;
		Double_t        Hodo19_TimeRawU;
		Double_t        Hodo19_TimeRawD;
		Double_t        Hodo20_Charge;
		Double_t        Hodo20_Charge_C;
		Double_t        Hodo20_ChargeU;
		Double_t        Hodo20_ChargeD;
		Double_t        Hodo20_Time;
		Double_t        Hodo20_Time_C;
		Double_t        Hodo20_ChargeCalU;
		Double_t        Hodo20_ChargeCalD;
		Double_t        Hodo20_TimeSlwU;
		Double_t        Hodo20_TimeSlwD;
		Double_t        Hodo20_TimeRawU;
		Double_t        Hodo20_TimeRawD;
		Double_t        Hodo21_Charge;
		Double_t        Hodo21_Charge_C;
		Double_t        Hodo21_ChargeU;
		Double_t        Hodo21_ChargeD;
		Double_t        Hodo21_Time;
		Double_t        Hodo21_Time_C;
		Double_t        Hodo21_ChargeCalU;
		Double_t        Hodo21_ChargeCalD;
		Double_t        Hodo21_TimeSlwU;
		Double_t        Hodo21_TimeSlwD;
		Double_t        Hodo21_TimeRawU;
		Double_t        Hodo21_TimeRawD;
		Double_t        Hodo22_Charge;
		Double_t        Hodo22_Charge_C;
		Double_t        Hodo22_ChargeU;
		Double_t        Hodo22_ChargeD;
		Double_t        Hodo22_Time;
		Double_t        Hodo22_Time_C;
		Double_t        Hodo22_ChargeCalU;
		Double_t        Hodo22_ChargeCalD;
		Double_t        Hodo22_TimeSlwU;
		Double_t        Hodo22_TimeSlwD;
		Double_t        Hodo22_TimeRawU;
		Double_t        Hodo22_TimeRawD;
		Double_t        Hodo23_Charge;
		Double_t        Hodo23_Charge_C;
		Double_t        Hodo23_ChargeU;
		Double_t        Hodo23_ChargeD;
		Double_t        Hodo23_Time;
		Double_t        Hodo23_Time_C;
		Double_t        Hodo23_ChargeCalU;
		Double_t        Hodo23_ChargeCalD;
		Double_t        Hodo23_TimeSlwU;
		Double_t        Hodo23_TimeSlwD;
		Double_t        Hodo23_TimeRawU;
		Double_t        Hodo23_TimeRawD;
		Double_t        Hodo24_Charge;
		Double_t        Hodo24_Charge_C;
		Double_t        Hodo24_ChargeU;
		Double_t        Hodo24_ChargeD;
		Double_t        Hodo24_Time;
		Double_t        Hodo24_Time_C;
		Double_t        Hodo24_ChargeCalU;
		Double_t        Hodo24_ChargeCalD;
		Double_t        Hodo24_TimeSlwU;
		Double_t        Hodo24_TimeSlwD;
		Double_t        Hodo24_TimeRawU;
		Double_t        Hodo24_TimeRawD;
		Double_t        Hodo25_Charge;
		Double_t        Hodo25_Charge_C;
		Double_t        Hodo25_ChargeU;
		Double_t        Hodo25_ChargeD;
		Double_t        Hodo25_Time;
		Double_t        Hodo25_Time_C;
		Double_t        Hodo25_ChargeCalU;
		Double_t        Hodo25_ChargeCalD;
		Double_t        Hodo25_TimeSlwU;
		Double_t        Hodo25_TimeSlwD;
		Double_t        Hodo25_TimeRawU;
		Double_t        Hodo25_TimeRawD;
		Double_t        Hodo26_Charge;
		Double_t        Hodo26_Charge_C;
		Double_t        Hodo26_ChargeU;
		Double_t        Hodo26_ChargeD;
		Double_t        Hodo26_Time;
		Double_t        Hodo26_Time_C;
		Double_t        Hodo26_ChargeCalU;
		Double_t        Hodo26_ChargeCalD;
		Double_t        Hodo26_TimeSlwU;
		Double_t        Hodo26_TimeSlwD;
		Double_t        Hodo26_TimeRawU;
		Double_t        Hodo26_TimeRawD;
		Double_t        Hodo27_Charge;
		Double_t        Hodo27_Charge_C;
		Double_t        Hodo27_ChargeU;
		Double_t        Hodo27_ChargeD;
		Double_t        Hodo27_Time;
		Double_t        Hodo27_Time_C;
		Double_t        Hodo27_ChargeCalU;
		Double_t        Hodo27_ChargeCalD;
		Double_t        Hodo27_TimeSlwU;
		Double_t        Hodo27_TimeSlwD;
		Double_t        Hodo27_TimeRawU;
		Double_t        Hodo27_TimeRawD;
		Double_t        Hodo28_Charge;
		Double_t        Hodo28_Charge_C;
		Double_t        Hodo28_ChargeU;
		Double_t        Hodo28_ChargeD;
		Double_t        Hodo28_Time;
		Double_t        Hodo28_Time_C;
		Double_t        Hodo28_ChargeCalU;
		Double_t        Hodo28_ChargeCalD;
		Double_t        Hodo28_TimeSlwU;
		Double_t        Hodo28_TimeSlwD;
		Double_t        Hodo28_TimeRawU;
		Double_t        Hodo28_TimeRawD;
		Double_t        Hodo29_Charge;
		Double_t        Hodo29_Charge_C;
		Double_t        Hodo29_ChargeU;
		Double_t        Hodo29_ChargeD;
		Double_t        Hodo29_Time;
		Double_t        Hodo29_Time_C;
		Double_t        Hodo29_ChargeCalU;
		Double_t        Hodo29_ChargeCalD;
		Double_t        Hodo29_TimeSlwU;
		Double_t        Hodo29_TimeSlwD;
		Double_t        Hodo29_TimeRawU;
		Double_t        Hodo29_TimeRawD;
		Double_t        Hodo30_Charge;
		Double_t        Hodo30_Charge_C;
		Double_t        Hodo30_ChargeU;
		Double_t        Hodo30_ChargeD;
		Double_t        Hodo30_Time;
		Double_t        Hodo30_Time_C;
		Double_t        Hodo30_ChargeCalU;
		Double_t        Hodo30_ChargeCalD;
		Double_t        Hodo30_TimeSlwU;
		Double_t        Hodo30_TimeSlwD;
		Double_t        Hodo30_TimeRawU;
		Double_t        Hodo30_TimeRawD;
		Double_t        Hodo31_Charge;
		Double_t        Hodo31_Charge_C;
		Double_t        Hodo31_ChargeU;
		Double_t        Hodo31_ChargeD;
		Double_t        Hodo31_Time;
		Double_t        Hodo31_Time_C;
		Double_t        Hodo31_ChargeCalU;
		Double_t        Hodo31_ChargeCalD;
		Double_t        Hodo31_TimeSlwU;
		Double_t        Hodo31_TimeSlwD;
		Double_t        Hodo31_TimeRawU;
		Double_t        Hodo31_TimeRawD;
		Double_t        Hodo32_Charge;
		Double_t        Hodo32_Charge_C;
		Double_t        Hodo32_ChargeU;
		Double_t        Hodo32_ChargeD;
		Double_t        Hodo32_Time;
		Double_t        Hodo32_Time_C;
		Double_t        Hodo32_ChargeCalU;
		Double_t        Hodo32_ChargeCalD;
		Double_t        Hodo32_TimeSlwU;
		Double_t        Hodo32_TimeSlwD;
		Double_t        Hodo32_TimeRawU;
		Double_t        Hodo32_TimeRawD;
		Double_t        Hodo33_Charge;
		Double_t        Hodo33_Charge_C;
		Double_t        Hodo33_ChargeU;
		Double_t        Hodo33_ChargeD;
		Double_t        Hodo33_Time;
		Double_t        Hodo33_Time_C;
		Double_t        Hodo33_ChargeCalU;
		Double_t        Hodo33_ChargeCalD;
		Double_t        Hodo33_TimeSlwU;
		Double_t        Hodo33_TimeSlwD;
		Double_t        Hodo33_TimeRawU;
		Double_t        Hodo33_TimeRawD;
		Double_t        Hodo34_Charge;
		Double_t        Hodo34_Charge_C;
		Double_t        Hodo34_ChargeU;
		Double_t        Hodo34_ChargeD;
		Double_t        Hodo34_Time;
		Double_t        Hodo34_Time_C;
		Double_t        Hodo34_ChargeCalU;
		Double_t        Hodo34_ChargeCalD;
		Double_t        Hodo34_TimeSlwU;
		Double_t        Hodo34_TimeSlwD;
		Double_t        Hodo34_TimeRawU;
		Double_t        Hodo34_TimeRawD;
		Double_t        Hodo35_Charge;
		Double_t        Hodo35_Charge_C;
		Double_t        Hodo35_ChargeU;
		Double_t        Hodo35_ChargeD;
		Double_t        Hodo35_Time;
		Double_t        Hodo35_Time_C;
		Double_t        Hodo35_ChargeCalU;
		Double_t        Hodo35_ChargeCalD;
		Double_t        Hodo35_TimeSlwU;
		Double_t        Hodo35_TimeSlwD;
		Double_t        Hodo35_TimeRawU;
		Double_t        Hodo35_TimeRawD;
		Double_t        Hodo36_Charge;
		Double_t        Hodo36_Charge_C;
		Double_t        Hodo36_ChargeU;
		Double_t        Hodo36_ChargeD;
		Double_t        Hodo36_Time;
		Double_t        Hodo36_Time_C;
		Double_t        Hodo36_ChargeCalU;
		Double_t        Hodo36_ChargeCalD;
		Double_t        Hodo36_TimeSlwU;
		Double_t        Hodo36_TimeSlwD;
		Double_t        Hodo36_TimeRawU;
		Double_t        Hodo36_TimeRawD;
		Double_t        Hodo37_Charge;
		Double_t        Hodo37_Charge_C;
		Double_t        Hodo37_ChargeU;
		Double_t        Hodo37_ChargeD;
		Double_t        Hodo37_Time;
		Double_t        Hodo37_Time_C;
		Double_t        Hodo37_ChargeCalU;
		Double_t        Hodo37_ChargeCalD;
		Double_t        Hodo37_TimeSlwU;
		Double_t        Hodo37_TimeSlwD;
		Double_t        Hodo37_TimeRawU;
		Double_t        Hodo37_TimeRawD;
		Double_t        Hodo38_Charge;
		Double_t        Hodo38_Charge_C;
		Double_t        Hodo38_ChargeU;
		Double_t        Hodo38_ChargeD;
		Double_t        Hodo38_Time;
		Double_t        Hodo38_Time_C;
		Double_t        Hodo38_ChargeCalU;
		Double_t        Hodo38_ChargeCalD;
		Double_t        Hodo38_TimeSlwU;
		Double_t        Hodo38_TimeSlwD;
		Double_t        Hodo38_TimeRawU;
		Double_t        Hodo38_TimeRawD;
		Double_t        Hodo39_Charge;
		Double_t        Hodo39_Charge_C;
		Double_t        Hodo39_ChargeU;
		Double_t        Hodo39_ChargeD;
		Double_t        Hodo39_Time;
		Double_t        Hodo39_Time_C;
		Double_t        Hodo39_ChargeCalU;
		Double_t        Hodo39_ChargeCalD;
		Double_t        Hodo39_TimeSlwU;
		Double_t        Hodo39_TimeSlwD;
		Double_t        Hodo39_TimeRawU;
		Double_t        Hodo39_TimeRawD;
		Double_t        Hodo40_Charge;
		Double_t        Hodo40_Charge_C;
		Double_t        Hodo40_ChargeU;
		Double_t        Hodo40_ChargeD;
		Double_t        Hodo40_Time;
		Double_t        Hodo40_Time_C;
		Double_t        Hodo40_ChargeCalU;
		Double_t        Hodo40_ChargeCalD;
		Double_t        Hodo40_TimeSlwU;
		Double_t        Hodo40_TimeSlwD;
		Double_t        Hodo40_TimeRawU;
		Double_t        Hodo40_TimeRawD;
		Int_t           Hodo_Multiplicity;
		Int_t           HodoP_Multiplicity;
		Int_t           HodoF_Multiplicity;
		Int_t           NUMBER_OF_HODO;
		Double_t        AllHodo_Charge[40];
		Double_t        AllHodo_Charge_C[40];
		Double_t        AllHodo_Time[40];
		Double_t        AllHodo_Time_C[40];
		Int_t           AllHodo_ID[40];
		Int_t           Hodo_ID;
		Int_t           HOD_GlobalID;
		Double_t        Hodo_Charge;
		Double_t        Hodo_Charge_C;
		Double_t        Hodo_ChargeP;
		Double_t        Hodo_ChargeF;
		Double_t        Hodo_Time;
		Double_t        Hodo_Time_C;
		Double_t        Hodo_Z;
		Double_t        Hodo_AoverZ;


		void setBranch(){
			// Set branch addresses.
			inputTree->SetBranchAddress("Hodo1_Charge",&Hodo1_Charge);
			inputTree->SetBranchAddress("Hodo1_Charge_C",&Hodo1_Charge_C);
			inputTree->SetBranchAddress("Hodo1_ChargeU",&Hodo1_ChargeU);
			inputTree->SetBranchAddress("Hodo1_ChargeD",&Hodo1_ChargeD);
			inputTree->SetBranchAddress("Hodo1_Time",&Hodo1_Time);
			inputTree->SetBranchAddress("Hodo1_Time_C",&Hodo1_Time_C);
			inputTree->SetBranchAddress("Hodo1_ChargeCalU",&Hodo1_ChargeCalU);
			inputTree->SetBranchAddress("Hodo1_ChargeCalD",&Hodo1_ChargeCalD);
			inputTree->SetBranchAddress("Hodo1_TimeSlwU",&Hodo1_TimeSlwU);
			inputTree->SetBranchAddress("Hodo1_TimeSlwD",&Hodo1_TimeSlwD);
			inputTree->SetBranchAddress("Hodo1_TimeRawU",&Hodo1_TimeRawU);
			inputTree->SetBranchAddress("Hodo1_TimeRawD",&Hodo1_TimeRawD);
			inputTree->SetBranchAddress("Hodo2_Charge",&Hodo2_Charge);
			inputTree->SetBranchAddress("Hodo2_Charge_C",&Hodo2_Charge_C);
			inputTree->SetBranchAddress("Hodo2_ChargeU",&Hodo2_ChargeU);
			inputTree->SetBranchAddress("Hodo2_ChargeD",&Hodo2_ChargeD);
			inputTree->SetBranchAddress("Hodo2_Time",&Hodo2_Time);
			inputTree->SetBranchAddress("Hodo2_Time_C",&Hodo2_Time_C);
			inputTree->SetBranchAddress("Hodo2_ChargeCalU",&Hodo2_ChargeCalU);
			inputTree->SetBranchAddress("Hodo2_ChargeCalD",&Hodo2_ChargeCalD);
			inputTree->SetBranchAddress("Hodo2_TimeSlwU",&Hodo2_TimeSlwU);
			inputTree->SetBranchAddress("Hodo2_TimeSlwD",&Hodo2_TimeSlwD);
			inputTree->SetBranchAddress("Hodo2_TimeRawU",&Hodo2_TimeRawU);
			inputTree->SetBranchAddress("Hodo2_TimeRawD",&Hodo2_TimeRawD);
			inputTree->SetBranchAddress("Hodo3_Charge",&Hodo3_Charge);
			inputTree->SetBranchAddress("Hodo3_Charge_C",&Hodo3_Charge_C);
			inputTree->SetBranchAddress("Hodo3_ChargeU",&Hodo3_ChargeU);
			inputTree->SetBranchAddress("Hodo3_ChargeD",&Hodo3_ChargeD);
			inputTree->SetBranchAddress("Hodo3_Time",&Hodo3_Time);
			inputTree->SetBranchAddress("Hodo3_Time_C",&Hodo3_Time_C);
			inputTree->SetBranchAddress("Hodo3_ChargeCalU",&Hodo3_ChargeCalU);
			inputTree->SetBranchAddress("Hodo3_ChargeCalD",&Hodo3_ChargeCalD);
			inputTree->SetBranchAddress("Hodo3_TimeSlwU",&Hodo3_TimeSlwU);
			inputTree->SetBranchAddress("Hodo3_TimeSlwD",&Hodo3_TimeSlwD);
			inputTree->SetBranchAddress("Hodo3_TimeRawU",&Hodo3_TimeRawU);
			inputTree->SetBranchAddress("Hodo3_TimeRawD",&Hodo3_TimeRawD);
			inputTree->SetBranchAddress("Hodo4_Charge",&Hodo4_Charge);
			inputTree->SetBranchAddress("Hodo4_Charge_C",&Hodo4_Charge_C);
			inputTree->SetBranchAddress("Hodo4_ChargeU",&Hodo4_ChargeU);
			inputTree->SetBranchAddress("Hodo4_ChargeD",&Hodo4_ChargeD);
			inputTree->SetBranchAddress("Hodo4_Time",&Hodo4_Time);
			inputTree->SetBranchAddress("Hodo4_Time_C",&Hodo4_Time_C);
			inputTree->SetBranchAddress("Hodo4_ChargeCalU",&Hodo4_ChargeCalU);
			inputTree->SetBranchAddress("Hodo4_ChargeCalD",&Hodo4_ChargeCalD);
			inputTree->SetBranchAddress("Hodo4_TimeSlwU",&Hodo4_TimeSlwU);
			inputTree->SetBranchAddress("Hodo4_TimeSlwD",&Hodo4_TimeSlwD);
			inputTree->SetBranchAddress("Hodo4_TimeRawU",&Hodo4_TimeRawU);
			inputTree->SetBranchAddress("Hodo4_TimeRawD",&Hodo4_TimeRawD);
			inputTree->SetBranchAddress("Hodo5_Charge",&Hodo5_Charge);
			inputTree->SetBranchAddress("Hodo5_Charge_C",&Hodo5_Charge_C);
			inputTree->SetBranchAddress("Hodo5_ChargeU",&Hodo5_ChargeU);
			inputTree->SetBranchAddress("Hodo5_ChargeD",&Hodo5_ChargeD);
			inputTree->SetBranchAddress("Hodo5_Time",&Hodo5_Time);
			inputTree->SetBranchAddress("Hodo5_Time_C",&Hodo5_Time_C);
			inputTree->SetBranchAddress("Hodo5_ChargeCalU",&Hodo5_ChargeCalU);
			inputTree->SetBranchAddress("Hodo5_ChargeCalD",&Hodo5_ChargeCalD);
			inputTree->SetBranchAddress("Hodo5_TimeSlwU",&Hodo5_TimeSlwU);
			inputTree->SetBranchAddress("Hodo5_TimeSlwD",&Hodo5_TimeSlwD);
			inputTree->SetBranchAddress("Hodo5_TimeRawU",&Hodo5_TimeRawU);
			inputTree->SetBranchAddress("Hodo5_TimeRawD",&Hodo5_TimeRawD);
			inputTree->SetBranchAddress("Hodo6_Charge",&Hodo6_Charge);
			inputTree->SetBranchAddress("Hodo6_Charge_C",&Hodo6_Charge_C);
			inputTree->SetBranchAddress("Hodo6_ChargeU",&Hodo6_ChargeU);
			inputTree->SetBranchAddress("Hodo6_ChargeD",&Hodo6_ChargeD);
			inputTree->SetBranchAddress("Hodo6_Time",&Hodo6_Time);
			inputTree->SetBranchAddress("Hodo6_Time_C",&Hodo6_Time_C);
			inputTree->SetBranchAddress("Hodo6_ChargeCalU",&Hodo6_ChargeCalU);
			inputTree->SetBranchAddress("Hodo6_ChargeCalD",&Hodo6_ChargeCalD);
			inputTree->SetBranchAddress("Hodo6_TimeSlwU",&Hodo6_TimeSlwU);
			inputTree->SetBranchAddress("Hodo6_TimeSlwD",&Hodo6_TimeSlwD);
			inputTree->SetBranchAddress("Hodo6_TimeRawU",&Hodo6_TimeRawU);
			inputTree->SetBranchAddress("Hodo6_TimeRawD",&Hodo6_TimeRawD);
			inputTree->SetBranchAddress("Hodo7_Charge",&Hodo7_Charge);
			inputTree->SetBranchAddress("Hodo7_Charge_C",&Hodo7_Charge_C);
			inputTree->SetBranchAddress("Hodo7_ChargeU",&Hodo7_ChargeU);
			inputTree->SetBranchAddress("Hodo7_ChargeD",&Hodo7_ChargeD);
			inputTree->SetBranchAddress("Hodo7_Time",&Hodo7_Time);
			inputTree->SetBranchAddress("Hodo7_Time_C",&Hodo7_Time_C);
			inputTree->SetBranchAddress("Hodo7_ChargeCalU",&Hodo7_ChargeCalU);
			inputTree->SetBranchAddress("Hodo7_ChargeCalD",&Hodo7_ChargeCalD);
			inputTree->SetBranchAddress("Hodo7_TimeSlwU",&Hodo7_TimeSlwU);
			inputTree->SetBranchAddress("Hodo7_TimeSlwD",&Hodo7_TimeSlwD);
			inputTree->SetBranchAddress("Hodo7_TimeRawU",&Hodo7_TimeRawU);
			inputTree->SetBranchAddress("Hodo7_TimeRawD",&Hodo7_TimeRawD);
			inputTree->SetBranchAddress("Hodo8_Charge",&Hodo8_Charge);
			inputTree->SetBranchAddress("Hodo8_Charge_C",&Hodo8_Charge_C);
			inputTree->SetBranchAddress("Hodo8_ChargeU",&Hodo8_ChargeU);
			inputTree->SetBranchAddress("Hodo8_ChargeD",&Hodo8_ChargeD);
			inputTree->SetBranchAddress("Hodo8_Time",&Hodo8_Time);
			inputTree->SetBranchAddress("Hodo8_Time_C",&Hodo8_Time_C);
			inputTree->SetBranchAddress("Hodo8_ChargeCalU",&Hodo8_ChargeCalU);
			inputTree->SetBranchAddress("Hodo8_ChargeCalD",&Hodo8_ChargeCalD);
			inputTree->SetBranchAddress("Hodo8_TimeSlwU",&Hodo8_TimeSlwU);
			inputTree->SetBranchAddress("Hodo8_TimeSlwD",&Hodo8_TimeSlwD);
			inputTree->SetBranchAddress("Hodo8_TimeRawU",&Hodo8_TimeRawU);
			inputTree->SetBranchAddress("Hodo8_TimeRawD",&Hodo8_TimeRawD);
			inputTree->SetBranchAddress("Hodo9_Charge",&Hodo9_Charge);
			inputTree->SetBranchAddress("Hodo9_Charge_C",&Hodo9_Charge_C);
			inputTree->SetBranchAddress("Hodo9_ChargeU",&Hodo9_ChargeU);
			inputTree->SetBranchAddress("Hodo9_ChargeD",&Hodo9_ChargeD);
			inputTree->SetBranchAddress("Hodo9_Time",&Hodo9_Time);
			inputTree->SetBranchAddress("Hodo9_Time_C",&Hodo9_Time_C);
			inputTree->SetBranchAddress("Hodo9_ChargeCalU",&Hodo9_ChargeCalU);
			inputTree->SetBranchAddress("Hodo9_ChargeCalD",&Hodo9_ChargeCalD);
			inputTree->SetBranchAddress("Hodo9_TimeSlwU",&Hodo9_TimeSlwU);
			inputTree->SetBranchAddress("Hodo9_TimeSlwD",&Hodo9_TimeSlwD);
			inputTree->SetBranchAddress("Hodo9_TimeRawU",&Hodo9_TimeRawU);
			inputTree->SetBranchAddress("Hodo9_TimeRawD",&Hodo9_TimeRawD);
			inputTree->SetBranchAddress("Hodo10_Charge",&Hodo10_Charge);
			inputTree->SetBranchAddress("Hodo10_Charge_C",&Hodo10_Charge_C);
			inputTree->SetBranchAddress("Hodo10_ChargeU",&Hodo10_ChargeU);
			inputTree->SetBranchAddress("Hodo10_ChargeD",&Hodo10_ChargeD);
			inputTree->SetBranchAddress("Hodo10_Time",&Hodo10_Time);
			inputTree->SetBranchAddress("Hodo10_Time_C",&Hodo10_Time_C);
			inputTree->SetBranchAddress("Hodo10_ChargeCalU",&Hodo10_ChargeCalU);
			inputTree->SetBranchAddress("Hodo10_ChargeCalD",&Hodo10_ChargeCalD);
			inputTree->SetBranchAddress("Hodo10_TimeSlwU",&Hodo10_TimeSlwU);
			inputTree->SetBranchAddress("Hodo10_TimeSlwD",&Hodo10_TimeSlwD);
			inputTree->SetBranchAddress("Hodo10_TimeRawU",&Hodo10_TimeRawU);
			inputTree->SetBranchAddress("Hodo10_TimeRawD",&Hodo10_TimeRawD);
			inputTree->SetBranchAddress("Hodo11_Charge",&Hodo11_Charge);
			inputTree->SetBranchAddress("Hodo11_Charge_C",&Hodo11_Charge_C);
			inputTree->SetBranchAddress("Hodo11_ChargeU",&Hodo11_ChargeU);
			inputTree->SetBranchAddress("Hodo11_ChargeD",&Hodo11_ChargeD);
			inputTree->SetBranchAddress("Hodo11_Time",&Hodo11_Time);
			inputTree->SetBranchAddress("Hodo11_Time_C",&Hodo11_Time_C);
			inputTree->SetBranchAddress("Hodo11_ChargeCalU",&Hodo11_ChargeCalU);
			inputTree->SetBranchAddress("Hodo11_ChargeCalD",&Hodo11_ChargeCalD);
			inputTree->SetBranchAddress("Hodo11_TimeSlwU",&Hodo11_TimeSlwU);
			inputTree->SetBranchAddress("Hodo11_TimeSlwD",&Hodo11_TimeSlwD);
			inputTree->SetBranchAddress("Hodo11_TimeRawU",&Hodo11_TimeRawU);
			inputTree->SetBranchAddress("Hodo11_TimeRawD",&Hodo11_TimeRawD);
			inputTree->SetBranchAddress("Hodo12_Charge",&Hodo12_Charge);
			inputTree->SetBranchAddress("Hodo12_Charge_C",&Hodo12_Charge_C);
			inputTree->SetBranchAddress("Hodo12_ChargeU",&Hodo12_ChargeU);
			inputTree->SetBranchAddress("Hodo12_ChargeD",&Hodo12_ChargeD);
			inputTree->SetBranchAddress("Hodo12_Time",&Hodo12_Time);
			inputTree->SetBranchAddress("Hodo12_Time_C",&Hodo12_Time_C);
			inputTree->SetBranchAddress("Hodo12_ChargeCalU",&Hodo12_ChargeCalU);
			inputTree->SetBranchAddress("Hodo12_ChargeCalD",&Hodo12_ChargeCalD);
			inputTree->SetBranchAddress("Hodo12_TimeSlwU",&Hodo12_TimeSlwU);
			inputTree->SetBranchAddress("Hodo12_TimeSlwD",&Hodo12_TimeSlwD);
			inputTree->SetBranchAddress("Hodo12_TimeRawU",&Hodo12_TimeRawU);
			inputTree->SetBranchAddress("Hodo12_TimeRawD",&Hodo12_TimeRawD);
			inputTree->SetBranchAddress("Hodo13_Charge",&Hodo13_Charge);
			inputTree->SetBranchAddress("Hodo13_Charge_C",&Hodo13_Charge_C);
			inputTree->SetBranchAddress("Hodo13_ChargeU",&Hodo13_ChargeU);
			inputTree->SetBranchAddress("Hodo13_ChargeD",&Hodo13_ChargeD);
			inputTree->SetBranchAddress("Hodo13_Time",&Hodo13_Time);
			inputTree->SetBranchAddress("Hodo13_Time_C",&Hodo13_Time_C);
			inputTree->SetBranchAddress("Hodo13_ChargeCalU",&Hodo13_ChargeCalU);
			inputTree->SetBranchAddress("Hodo13_ChargeCalD",&Hodo13_ChargeCalD);
			inputTree->SetBranchAddress("Hodo13_TimeSlwU",&Hodo13_TimeSlwU);
			inputTree->SetBranchAddress("Hodo13_TimeSlwD",&Hodo13_TimeSlwD);
			inputTree->SetBranchAddress("Hodo13_TimeRawU",&Hodo13_TimeRawU);
			inputTree->SetBranchAddress("Hodo13_TimeRawD",&Hodo13_TimeRawD);
			inputTree->SetBranchAddress("Hodo14_Charge",&Hodo14_Charge);
			inputTree->SetBranchAddress("Hodo14_Charge_C",&Hodo14_Charge_C);
			inputTree->SetBranchAddress("Hodo14_ChargeU",&Hodo14_ChargeU);
			inputTree->SetBranchAddress("Hodo14_ChargeD",&Hodo14_ChargeD);
			inputTree->SetBranchAddress("Hodo14_Time",&Hodo14_Time);
			inputTree->SetBranchAddress("Hodo14_Time_C",&Hodo14_Time_C);
			inputTree->SetBranchAddress("Hodo14_ChargeCalU",&Hodo14_ChargeCalU);
			inputTree->SetBranchAddress("Hodo14_ChargeCalD",&Hodo14_ChargeCalD);
			inputTree->SetBranchAddress("Hodo14_TimeSlwU",&Hodo14_TimeSlwU);
			inputTree->SetBranchAddress("Hodo14_TimeSlwD",&Hodo14_TimeSlwD);
			inputTree->SetBranchAddress("Hodo14_TimeRawU",&Hodo14_TimeRawU);
			inputTree->SetBranchAddress("Hodo14_TimeRawD",&Hodo14_TimeRawD);
			inputTree->SetBranchAddress("Hodo15_Charge",&Hodo15_Charge);
			inputTree->SetBranchAddress("Hodo15_Charge_C",&Hodo15_Charge_C);
			inputTree->SetBranchAddress("Hodo15_ChargeU",&Hodo15_ChargeU);
			inputTree->SetBranchAddress("Hodo15_ChargeD",&Hodo15_ChargeD);
			inputTree->SetBranchAddress("Hodo15_Time",&Hodo15_Time);
			inputTree->SetBranchAddress("Hodo15_Time_C",&Hodo15_Time_C);
			inputTree->SetBranchAddress("Hodo15_ChargeCalU",&Hodo15_ChargeCalU);
			inputTree->SetBranchAddress("Hodo15_ChargeCalD",&Hodo15_ChargeCalD);
			inputTree->SetBranchAddress("Hodo15_TimeSlwU",&Hodo15_TimeSlwU);
			inputTree->SetBranchAddress("Hodo15_TimeSlwD",&Hodo15_TimeSlwD);
			inputTree->SetBranchAddress("Hodo15_TimeRawU",&Hodo15_TimeRawU);
			inputTree->SetBranchAddress("Hodo15_TimeRawD",&Hodo15_TimeRawD);
			inputTree->SetBranchAddress("Hodo16_Charge",&Hodo16_Charge);
			inputTree->SetBranchAddress("Hodo16_Charge_C",&Hodo16_Charge_C);
			inputTree->SetBranchAddress("Hodo16_ChargeU",&Hodo16_ChargeU);
			inputTree->SetBranchAddress("Hodo16_ChargeD",&Hodo16_ChargeD);
			inputTree->SetBranchAddress("Hodo16_Time",&Hodo16_Time);
			inputTree->SetBranchAddress("Hodo16_Time_C",&Hodo16_Time_C);
			inputTree->SetBranchAddress("Hodo16_ChargeCalU",&Hodo16_ChargeCalU);
			inputTree->SetBranchAddress("Hodo16_ChargeCalD",&Hodo16_ChargeCalD);
			inputTree->SetBranchAddress("Hodo16_TimeSlwU",&Hodo16_TimeSlwU);
			inputTree->SetBranchAddress("Hodo16_TimeSlwD",&Hodo16_TimeSlwD);
			inputTree->SetBranchAddress("Hodo16_TimeRawU",&Hodo16_TimeRawU);
			inputTree->SetBranchAddress("Hodo16_TimeRawD",&Hodo16_TimeRawD);
			inputTree->SetBranchAddress("Hodo17_Charge",&Hodo17_Charge);
			inputTree->SetBranchAddress("Hodo17_Charge_C",&Hodo17_Charge_C);
			inputTree->SetBranchAddress("Hodo17_ChargeU",&Hodo17_ChargeU);
			inputTree->SetBranchAddress("Hodo17_ChargeD",&Hodo17_ChargeD);
			inputTree->SetBranchAddress("Hodo17_Time",&Hodo17_Time);
			inputTree->SetBranchAddress("Hodo17_Time_C",&Hodo17_Time_C);
			inputTree->SetBranchAddress("Hodo17_ChargeCalU",&Hodo17_ChargeCalU);
			inputTree->SetBranchAddress("Hodo17_ChargeCalD",&Hodo17_ChargeCalD);
			inputTree->SetBranchAddress("Hodo17_TimeSlwU",&Hodo17_TimeSlwU);
			inputTree->SetBranchAddress("Hodo17_TimeSlwD",&Hodo17_TimeSlwD);
			inputTree->SetBranchAddress("Hodo17_TimeRawU",&Hodo17_TimeRawU);
			inputTree->SetBranchAddress("Hodo17_TimeRawD",&Hodo17_TimeRawD);
			inputTree->SetBranchAddress("Hodo18_Charge",&Hodo18_Charge);
			inputTree->SetBranchAddress("Hodo18_Charge_C",&Hodo18_Charge_C);
			inputTree->SetBranchAddress("Hodo18_ChargeU",&Hodo18_ChargeU);
			inputTree->SetBranchAddress("Hodo18_ChargeD",&Hodo18_ChargeD);
			inputTree->SetBranchAddress("Hodo18_Time",&Hodo18_Time);
			inputTree->SetBranchAddress("Hodo18_Time_C",&Hodo18_Time_C);
			inputTree->SetBranchAddress("Hodo18_ChargeCalU",&Hodo18_ChargeCalU);
			inputTree->SetBranchAddress("Hodo18_ChargeCalD",&Hodo18_ChargeCalD);
			inputTree->SetBranchAddress("Hodo18_TimeSlwU",&Hodo18_TimeSlwU);
			inputTree->SetBranchAddress("Hodo18_TimeSlwD",&Hodo18_TimeSlwD);
			inputTree->SetBranchAddress("Hodo18_TimeRawU",&Hodo18_TimeRawU);
			inputTree->SetBranchAddress("Hodo18_TimeRawD",&Hodo18_TimeRawD);
			inputTree->SetBranchAddress("Hodo19_Charge",&Hodo19_Charge);
			inputTree->SetBranchAddress("Hodo19_Charge_C",&Hodo19_Charge_C);
			inputTree->SetBranchAddress("Hodo19_ChargeU",&Hodo19_ChargeU);
			inputTree->SetBranchAddress("Hodo19_ChargeD",&Hodo19_ChargeD);
			inputTree->SetBranchAddress("Hodo19_Time",&Hodo19_Time);
			inputTree->SetBranchAddress("Hodo19_Time_C",&Hodo19_Time_C);
			inputTree->SetBranchAddress("Hodo19_ChargeCalU",&Hodo19_ChargeCalU);
			inputTree->SetBranchAddress("Hodo19_ChargeCalD",&Hodo19_ChargeCalD);
			inputTree->SetBranchAddress("Hodo19_TimeSlwU",&Hodo19_TimeSlwU);
			inputTree->SetBranchAddress("Hodo19_TimeSlwD",&Hodo19_TimeSlwD);
			inputTree->SetBranchAddress("Hodo19_TimeRawU",&Hodo19_TimeRawU);
			inputTree->SetBranchAddress("Hodo19_TimeRawD",&Hodo19_TimeRawD);
			inputTree->SetBranchAddress("Hodo20_Charge",&Hodo20_Charge);
			inputTree->SetBranchAddress("Hodo20_Charge_C",&Hodo20_Charge_C);
			inputTree->SetBranchAddress("Hodo20_ChargeU",&Hodo20_ChargeU);
			inputTree->SetBranchAddress("Hodo20_ChargeD",&Hodo20_ChargeD);
			inputTree->SetBranchAddress("Hodo20_Time",&Hodo20_Time);
			inputTree->SetBranchAddress("Hodo20_Time_C",&Hodo20_Time_C);
			inputTree->SetBranchAddress("Hodo20_ChargeCalU",&Hodo20_ChargeCalU);
			inputTree->SetBranchAddress("Hodo20_ChargeCalD",&Hodo20_ChargeCalD);
			inputTree->SetBranchAddress("Hodo20_TimeSlwU",&Hodo20_TimeSlwU);
			inputTree->SetBranchAddress("Hodo20_TimeSlwD",&Hodo20_TimeSlwD);
			inputTree->SetBranchAddress("Hodo20_TimeRawU",&Hodo20_TimeRawU);
			inputTree->SetBranchAddress("Hodo20_TimeRawD",&Hodo20_TimeRawD);
			inputTree->SetBranchAddress("Hodo21_Charge",&Hodo21_Charge);
			inputTree->SetBranchAddress("Hodo21_Charge_C",&Hodo21_Charge_C);
			inputTree->SetBranchAddress("Hodo21_ChargeU",&Hodo21_ChargeU);
			inputTree->SetBranchAddress("Hodo21_ChargeD",&Hodo21_ChargeD);
			inputTree->SetBranchAddress("Hodo21_Time",&Hodo21_Time);
			inputTree->SetBranchAddress("Hodo21_Time_C",&Hodo21_Time_C);
			inputTree->SetBranchAddress("Hodo21_ChargeCalU",&Hodo21_ChargeCalU);
			inputTree->SetBranchAddress("Hodo21_ChargeCalD",&Hodo21_ChargeCalD);
			inputTree->SetBranchAddress("Hodo21_TimeSlwU",&Hodo21_TimeSlwU);
			inputTree->SetBranchAddress("Hodo21_TimeSlwD",&Hodo21_TimeSlwD);
			inputTree->SetBranchAddress("Hodo21_TimeRawU",&Hodo21_TimeRawU);
			inputTree->SetBranchAddress("Hodo21_TimeRawD",&Hodo21_TimeRawD);
			inputTree->SetBranchAddress("Hodo22_Charge",&Hodo22_Charge);
			inputTree->SetBranchAddress("Hodo22_Charge_C",&Hodo22_Charge_C);
			inputTree->SetBranchAddress("Hodo22_ChargeU",&Hodo22_ChargeU);
			inputTree->SetBranchAddress("Hodo22_ChargeD",&Hodo22_ChargeD);
			inputTree->SetBranchAddress("Hodo22_Time",&Hodo22_Time);
			inputTree->SetBranchAddress("Hodo22_Time_C",&Hodo22_Time_C);
			inputTree->SetBranchAddress("Hodo22_ChargeCalU",&Hodo22_ChargeCalU);
			inputTree->SetBranchAddress("Hodo22_ChargeCalD",&Hodo22_ChargeCalD);
			inputTree->SetBranchAddress("Hodo22_TimeSlwU",&Hodo22_TimeSlwU);
			inputTree->SetBranchAddress("Hodo22_TimeSlwD",&Hodo22_TimeSlwD);
			inputTree->SetBranchAddress("Hodo22_TimeRawU",&Hodo22_TimeRawU);
			inputTree->SetBranchAddress("Hodo22_TimeRawD",&Hodo22_TimeRawD);
			inputTree->SetBranchAddress("Hodo23_Charge",&Hodo23_Charge);
			inputTree->SetBranchAddress("Hodo23_Charge_C",&Hodo23_Charge_C);
			inputTree->SetBranchAddress("Hodo23_ChargeU",&Hodo23_ChargeU);
			inputTree->SetBranchAddress("Hodo23_ChargeD",&Hodo23_ChargeD);
			inputTree->SetBranchAddress("Hodo23_Time",&Hodo23_Time);
			inputTree->SetBranchAddress("Hodo23_Time_C",&Hodo23_Time_C);
			inputTree->SetBranchAddress("Hodo23_ChargeCalU",&Hodo23_ChargeCalU);
			inputTree->SetBranchAddress("Hodo23_ChargeCalD",&Hodo23_ChargeCalD);
			inputTree->SetBranchAddress("Hodo23_TimeSlwU",&Hodo23_TimeSlwU);
			inputTree->SetBranchAddress("Hodo23_TimeSlwD",&Hodo23_TimeSlwD);
			inputTree->SetBranchAddress("Hodo23_TimeRawU",&Hodo23_TimeRawU);
			inputTree->SetBranchAddress("Hodo23_TimeRawD",&Hodo23_TimeRawD);
			inputTree->SetBranchAddress("Hodo24_Charge",&Hodo24_Charge);
			inputTree->SetBranchAddress("Hodo24_Charge_C",&Hodo24_Charge_C);
			inputTree->SetBranchAddress("Hodo24_ChargeU",&Hodo24_ChargeU);
			inputTree->SetBranchAddress("Hodo24_ChargeD",&Hodo24_ChargeD);
			inputTree->SetBranchAddress("Hodo24_Time",&Hodo24_Time);
			inputTree->SetBranchAddress("Hodo24_Time_C",&Hodo24_Time_C);
			inputTree->SetBranchAddress("Hodo24_ChargeCalU",&Hodo24_ChargeCalU);
			inputTree->SetBranchAddress("Hodo24_ChargeCalD",&Hodo24_ChargeCalD);
			inputTree->SetBranchAddress("Hodo24_TimeSlwU",&Hodo24_TimeSlwU);
			inputTree->SetBranchAddress("Hodo24_TimeSlwD",&Hodo24_TimeSlwD);
			inputTree->SetBranchAddress("Hodo24_TimeRawU",&Hodo24_TimeRawU);
			inputTree->SetBranchAddress("Hodo24_TimeRawD",&Hodo24_TimeRawD);
			inputTree->SetBranchAddress("Hodo25_Charge",&Hodo25_Charge);
			inputTree->SetBranchAddress("Hodo25_Charge_C",&Hodo25_Charge_C);
			inputTree->SetBranchAddress("Hodo25_ChargeU",&Hodo25_ChargeU);
			inputTree->SetBranchAddress("Hodo25_ChargeD",&Hodo25_ChargeD);
			inputTree->SetBranchAddress("Hodo25_Time",&Hodo25_Time);
			inputTree->SetBranchAddress("Hodo25_Time_C",&Hodo25_Time_C);
			inputTree->SetBranchAddress("Hodo25_ChargeCalU",&Hodo25_ChargeCalU);
			inputTree->SetBranchAddress("Hodo25_ChargeCalD",&Hodo25_ChargeCalD);
			inputTree->SetBranchAddress("Hodo25_TimeSlwU",&Hodo25_TimeSlwU);
			inputTree->SetBranchAddress("Hodo25_TimeSlwD",&Hodo25_TimeSlwD);
			inputTree->SetBranchAddress("Hodo25_TimeRawU",&Hodo25_TimeRawU);
			inputTree->SetBranchAddress("Hodo25_TimeRawD",&Hodo25_TimeRawD);
			inputTree->SetBranchAddress("Hodo26_Charge",&Hodo26_Charge);
			inputTree->SetBranchAddress("Hodo26_Charge_C",&Hodo26_Charge_C);
			inputTree->SetBranchAddress("Hodo26_ChargeU",&Hodo26_ChargeU);
			inputTree->SetBranchAddress("Hodo26_ChargeD",&Hodo26_ChargeD);
			inputTree->SetBranchAddress("Hodo26_Time",&Hodo26_Time);
			inputTree->SetBranchAddress("Hodo26_Time_C",&Hodo26_Time_C);
			inputTree->SetBranchAddress("Hodo26_ChargeCalU",&Hodo26_ChargeCalU);
			inputTree->SetBranchAddress("Hodo26_ChargeCalD",&Hodo26_ChargeCalD);
			inputTree->SetBranchAddress("Hodo26_TimeSlwU",&Hodo26_TimeSlwU);
			inputTree->SetBranchAddress("Hodo26_TimeSlwD",&Hodo26_TimeSlwD);
			inputTree->SetBranchAddress("Hodo26_TimeRawU",&Hodo26_TimeRawU);
			inputTree->SetBranchAddress("Hodo26_TimeRawD",&Hodo26_TimeRawD);
			inputTree->SetBranchAddress("Hodo27_Charge",&Hodo27_Charge);
			inputTree->SetBranchAddress("Hodo27_Charge_C",&Hodo27_Charge_C);
			inputTree->SetBranchAddress("Hodo27_ChargeU",&Hodo27_ChargeU);
			inputTree->SetBranchAddress("Hodo27_ChargeD",&Hodo27_ChargeD);
			inputTree->SetBranchAddress("Hodo27_Time",&Hodo27_Time);
			inputTree->SetBranchAddress("Hodo27_Time_C",&Hodo27_Time_C);
			inputTree->SetBranchAddress("Hodo27_ChargeCalU",&Hodo27_ChargeCalU);
			inputTree->SetBranchAddress("Hodo27_ChargeCalD",&Hodo27_ChargeCalD);
			inputTree->SetBranchAddress("Hodo27_TimeSlwU",&Hodo27_TimeSlwU);
			inputTree->SetBranchAddress("Hodo27_TimeSlwD",&Hodo27_TimeSlwD);
			inputTree->SetBranchAddress("Hodo27_TimeRawU",&Hodo27_TimeRawU);
			inputTree->SetBranchAddress("Hodo27_TimeRawD",&Hodo27_TimeRawD);
			inputTree->SetBranchAddress("Hodo28_Charge",&Hodo28_Charge);
			inputTree->SetBranchAddress("Hodo28_Charge_C",&Hodo28_Charge_C);
			inputTree->SetBranchAddress("Hodo28_ChargeU",&Hodo28_ChargeU);
			inputTree->SetBranchAddress("Hodo28_ChargeD",&Hodo28_ChargeD);
			inputTree->SetBranchAddress("Hodo28_Time",&Hodo28_Time);
			inputTree->SetBranchAddress("Hodo28_Time_C",&Hodo28_Time_C);
			inputTree->SetBranchAddress("Hodo28_ChargeCalU",&Hodo28_ChargeCalU);
			inputTree->SetBranchAddress("Hodo28_ChargeCalD",&Hodo28_ChargeCalD);
			inputTree->SetBranchAddress("Hodo28_TimeSlwU",&Hodo28_TimeSlwU);
			inputTree->SetBranchAddress("Hodo28_TimeSlwD",&Hodo28_TimeSlwD);
			inputTree->SetBranchAddress("Hodo28_TimeRawU",&Hodo28_TimeRawU);
			inputTree->SetBranchAddress("Hodo28_TimeRawD",&Hodo28_TimeRawD);
			inputTree->SetBranchAddress("Hodo29_Charge",&Hodo29_Charge);
			inputTree->SetBranchAddress("Hodo29_Charge_C",&Hodo29_Charge_C);
			inputTree->SetBranchAddress("Hodo29_ChargeU",&Hodo29_ChargeU);
			inputTree->SetBranchAddress("Hodo29_ChargeD",&Hodo29_ChargeD);
			inputTree->SetBranchAddress("Hodo29_Time",&Hodo29_Time);
			inputTree->SetBranchAddress("Hodo29_Time_C",&Hodo29_Time_C);
			inputTree->SetBranchAddress("Hodo29_ChargeCalU",&Hodo29_ChargeCalU);
			inputTree->SetBranchAddress("Hodo29_ChargeCalD",&Hodo29_ChargeCalD);
			inputTree->SetBranchAddress("Hodo29_TimeSlwU",&Hodo29_TimeSlwU);
			inputTree->SetBranchAddress("Hodo29_TimeSlwD",&Hodo29_TimeSlwD);
			inputTree->SetBranchAddress("Hodo29_TimeRawU",&Hodo29_TimeRawU);
			inputTree->SetBranchAddress("Hodo29_TimeRawD",&Hodo29_TimeRawD);
			inputTree->SetBranchAddress("Hodo30_Charge",&Hodo30_Charge);
			inputTree->SetBranchAddress("Hodo30_Charge_C",&Hodo30_Charge_C);
			inputTree->SetBranchAddress("Hodo30_ChargeU",&Hodo30_ChargeU);
			inputTree->SetBranchAddress("Hodo30_ChargeD",&Hodo30_ChargeD);
			inputTree->SetBranchAddress("Hodo30_Time",&Hodo30_Time);
			inputTree->SetBranchAddress("Hodo30_Time_C",&Hodo30_Time_C);
			inputTree->SetBranchAddress("Hodo30_ChargeCalU",&Hodo30_ChargeCalU);
			inputTree->SetBranchAddress("Hodo30_ChargeCalD",&Hodo30_ChargeCalD);
			inputTree->SetBranchAddress("Hodo30_TimeSlwU",&Hodo30_TimeSlwU);
			inputTree->SetBranchAddress("Hodo30_TimeSlwD",&Hodo30_TimeSlwD);
			inputTree->SetBranchAddress("Hodo30_TimeRawU",&Hodo30_TimeRawU);
			inputTree->SetBranchAddress("Hodo30_TimeRawD",&Hodo30_TimeRawD);
			inputTree->SetBranchAddress("Hodo31_Charge",&Hodo31_Charge);
			inputTree->SetBranchAddress("Hodo31_Charge_C",&Hodo31_Charge_C);
			inputTree->SetBranchAddress("Hodo31_ChargeU",&Hodo31_ChargeU);
			inputTree->SetBranchAddress("Hodo31_ChargeD",&Hodo31_ChargeD);
			inputTree->SetBranchAddress("Hodo31_Time",&Hodo31_Time);
			inputTree->SetBranchAddress("Hodo31_Time_C",&Hodo31_Time_C);
			inputTree->SetBranchAddress("Hodo31_ChargeCalU",&Hodo31_ChargeCalU);
			inputTree->SetBranchAddress("Hodo31_ChargeCalD",&Hodo31_ChargeCalD);
			inputTree->SetBranchAddress("Hodo31_TimeSlwU",&Hodo31_TimeSlwU);
			inputTree->SetBranchAddress("Hodo31_TimeSlwD",&Hodo31_TimeSlwD);
			inputTree->SetBranchAddress("Hodo31_TimeRawU",&Hodo31_TimeRawU);
			inputTree->SetBranchAddress("Hodo31_TimeRawD",&Hodo31_TimeRawD);
			inputTree->SetBranchAddress("Hodo32_Charge",&Hodo32_Charge);
			inputTree->SetBranchAddress("Hodo32_Charge_C",&Hodo32_Charge_C);
			inputTree->SetBranchAddress("Hodo32_ChargeU",&Hodo32_ChargeU);
			inputTree->SetBranchAddress("Hodo32_ChargeD",&Hodo32_ChargeD);
			inputTree->SetBranchAddress("Hodo32_Time",&Hodo32_Time);
			inputTree->SetBranchAddress("Hodo32_Time_C",&Hodo32_Time_C);
			inputTree->SetBranchAddress("Hodo32_ChargeCalU",&Hodo32_ChargeCalU);
			inputTree->SetBranchAddress("Hodo32_ChargeCalD",&Hodo32_ChargeCalD);
			inputTree->SetBranchAddress("Hodo32_TimeSlwU",&Hodo32_TimeSlwU);
			inputTree->SetBranchAddress("Hodo32_TimeSlwD",&Hodo32_TimeSlwD);
			inputTree->SetBranchAddress("Hodo32_TimeRawU",&Hodo32_TimeRawU);
			inputTree->SetBranchAddress("Hodo32_TimeRawD",&Hodo32_TimeRawD);
			inputTree->SetBranchAddress("Hodo33_Charge",&Hodo33_Charge);
			inputTree->SetBranchAddress("Hodo33_Charge_C",&Hodo33_Charge_C);
			inputTree->SetBranchAddress("Hodo33_ChargeU",&Hodo33_ChargeU);
			inputTree->SetBranchAddress("Hodo33_ChargeD",&Hodo33_ChargeD);
			inputTree->SetBranchAddress("Hodo33_Time",&Hodo33_Time);
			inputTree->SetBranchAddress("Hodo33_Time_C",&Hodo33_Time_C);
			inputTree->SetBranchAddress("Hodo33_ChargeCalU",&Hodo33_ChargeCalU);
			inputTree->SetBranchAddress("Hodo33_ChargeCalD",&Hodo33_ChargeCalD);
			inputTree->SetBranchAddress("Hodo33_TimeSlwU",&Hodo33_TimeSlwU);
			inputTree->SetBranchAddress("Hodo33_TimeSlwD",&Hodo33_TimeSlwD);
			inputTree->SetBranchAddress("Hodo33_TimeRawU",&Hodo33_TimeRawU);
			inputTree->SetBranchAddress("Hodo33_TimeRawD",&Hodo33_TimeRawD);
			inputTree->SetBranchAddress("Hodo34_Charge",&Hodo34_Charge);
			inputTree->SetBranchAddress("Hodo34_Charge_C",&Hodo34_Charge_C);
			inputTree->SetBranchAddress("Hodo34_ChargeU",&Hodo34_ChargeU);
			inputTree->SetBranchAddress("Hodo34_ChargeD",&Hodo34_ChargeD);
			inputTree->SetBranchAddress("Hodo34_Time",&Hodo34_Time);
			inputTree->SetBranchAddress("Hodo34_Time_C",&Hodo34_Time_C);
			inputTree->SetBranchAddress("Hodo34_ChargeCalU",&Hodo34_ChargeCalU);
			inputTree->SetBranchAddress("Hodo34_ChargeCalD",&Hodo34_ChargeCalD);
			inputTree->SetBranchAddress("Hodo34_TimeSlwU",&Hodo34_TimeSlwU);
			inputTree->SetBranchAddress("Hodo34_TimeSlwD",&Hodo34_TimeSlwD);
			inputTree->SetBranchAddress("Hodo34_TimeRawU",&Hodo34_TimeRawU);
			inputTree->SetBranchAddress("Hodo34_TimeRawD",&Hodo34_TimeRawD);
			inputTree->SetBranchAddress("Hodo35_Charge",&Hodo35_Charge);
			inputTree->SetBranchAddress("Hodo35_Charge_C",&Hodo35_Charge_C);
			inputTree->SetBranchAddress("Hodo35_ChargeU",&Hodo35_ChargeU);
			inputTree->SetBranchAddress("Hodo35_ChargeD",&Hodo35_ChargeD);
			inputTree->SetBranchAddress("Hodo35_Time",&Hodo35_Time);
			inputTree->SetBranchAddress("Hodo35_Time_C",&Hodo35_Time_C);
			inputTree->SetBranchAddress("Hodo35_ChargeCalU",&Hodo35_ChargeCalU);
			inputTree->SetBranchAddress("Hodo35_ChargeCalD",&Hodo35_ChargeCalD);
			inputTree->SetBranchAddress("Hodo35_TimeSlwU",&Hodo35_TimeSlwU);
			inputTree->SetBranchAddress("Hodo35_TimeSlwD",&Hodo35_TimeSlwD);
			inputTree->SetBranchAddress("Hodo35_TimeRawU",&Hodo35_TimeRawU);
			inputTree->SetBranchAddress("Hodo35_TimeRawD",&Hodo35_TimeRawD);
			inputTree->SetBranchAddress("Hodo36_Charge",&Hodo36_Charge);
			inputTree->SetBranchAddress("Hodo36_Charge_C",&Hodo36_Charge_C);
			inputTree->SetBranchAddress("Hodo36_ChargeU",&Hodo36_ChargeU);
			inputTree->SetBranchAddress("Hodo36_ChargeD",&Hodo36_ChargeD);
			inputTree->SetBranchAddress("Hodo36_Time",&Hodo36_Time);
			inputTree->SetBranchAddress("Hodo36_Time_C",&Hodo36_Time_C);
			inputTree->SetBranchAddress("Hodo36_ChargeCalU",&Hodo36_ChargeCalU);
			inputTree->SetBranchAddress("Hodo36_ChargeCalD",&Hodo36_ChargeCalD);
			inputTree->SetBranchAddress("Hodo36_TimeSlwU",&Hodo36_TimeSlwU);
			inputTree->SetBranchAddress("Hodo36_TimeSlwD",&Hodo36_TimeSlwD);
			inputTree->SetBranchAddress("Hodo36_TimeRawU",&Hodo36_TimeRawU);
			inputTree->SetBranchAddress("Hodo36_TimeRawD",&Hodo36_TimeRawD);
			inputTree->SetBranchAddress("Hodo37_Charge",&Hodo37_Charge);
			inputTree->SetBranchAddress("Hodo37_Charge_C",&Hodo37_Charge_C);
			inputTree->SetBranchAddress("Hodo37_ChargeU",&Hodo37_ChargeU);
			inputTree->SetBranchAddress("Hodo37_ChargeD",&Hodo37_ChargeD);
			inputTree->SetBranchAddress("Hodo37_Time",&Hodo37_Time);
			inputTree->SetBranchAddress("Hodo37_Time_C",&Hodo37_Time_C);
			inputTree->SetBranchAddress("Hodo37_ChargeCalU",&Hodo37_ChargeCalU);
			inputTree->SetBranchAddress("Hodo37_ChargeCalD",&Hodo37_ChargeCalD);
			inputTree->SetBranchAddress("Hodo37_TimeSlwU",&Hodo37_TimeSlwU);
			inputTree->SetBranchAddress("Hodo37_TimeSlwD",&Hodo37_TimeSlwD);
			inputTree->SetBranchAddress("Hodo37_TimeRawU",&Hodo37_TimeRawU);
			inputTree->SetBranchAddress("Hodo37_TimeRawD",&Hodo37_TimeRawD);
			inputTree->SetBranchAddress("Hodo38_Charge",&Hodo38_Charge);
			inputTree->SetBranchAddress("Hodo38_Charge_C",&Hodo38_Charge_C);
			inputTree->SetBranchAddress("Hodo38_ChargeU",&Hodo38_ChargeU);
			inputTree->SetBranchAddress("Hodo38_ChargeD",&Hodo38_ChargeD);
			inputTree->SetBranchAddress("Hodo38_Time",&Hodo38_Time);
			inputTree->SetBranchAddress("Hodo38_Time_C",&Hodo38_Time_C);
			inputTree->SetBranchAddress("Hodo38_ChargeCalU",&Hodo38_ChargeCalU);
			inputTree->SetBranchAddress("Hodo38_ChargeCalD",&Hodo38_ChargeCalD);
			inputTree->SetBranchAddress("Hodo38_TimeSlwU",&Hodo38_TimeSlwU);
			inputTree->SetBranchAddress("Hodo38_TimeSlwD",&Hodo38_TimeSlwD);
			inputTree->SetBranchAddress("Hodo38_TimeRawU",&Hodo38_TimeRawU);
			inputTree->SetBranchAddress("Hodo38_TimeRawD",&Hodo38_TimeRawD);
			inputTree->SetBranchAddress("Hodo39_Charge",&Hodo39_Charge);
			inputTree->SetBranchAddress("Hodo39_Charge_C",&Hodo39_Charge_C);
			inputTree->SetBranchAddress("Hodo39_ChargeU",&Hodo39_ChargeU);
			inputTree->SetBranchAddress("Hodo39_ChargeD",&Hodo39_ChargeD);
			inputTree->SetBranchAddress("Hodo39_Time",&Hodo39_Time);
			inputTree->SetBranchAddress("Hodo39_Time_C",&Hodo39_Time_C);
			inputTree->SetBranchAddress("Hodo39_ChargeCalU",&Hodo39_ChargeCalU);
			inputTree->SetBranchAddress("Hodo39_ChargeCalD",&Hodo39_ChargeCalD);
			inputTree->SetBranchAddress("Hodo39_TimeSlwU",&Hodo39_TimeSlwU);
			inputTree->SetBranchAddress("Hodo39_TimeSlwD",&Hodo39_TimeSlwD);
			inputTree->SetBranchAddress("Hodo39_TimeRawU",&Hodo39_TimeRawU);
			inputTree->SetBranchAddress("Hodo39_TimeRawD",&Hodo39_TimeRawD);
			inputTree->SetBranchAddress("Hodo40_Charge",&Hodo40_Charge);
			inputTree->SetBranchAddress("Hodo40_Charge_C",&Hodo40_Charge_C);
			inputTree->SetBranchAddress("Hodo40_ChargeU",&Hodo40_ChargeU);
			inputTree->SetBranchAddress("Hodo40_ChargeD",&Hodo40_ChargeD);
			inputTree->SetBranchAddress("Hodo40_Time",&Hodo40_Time);
			inputTree->SetBranchAddress("Hodo40_Time_C",&Hodo40_Time_C);
			inputTree->SetBranchAddress("Hodo40_ChargeCalU",&Hodo40_ChargeCalU);
			inputTree->SetBranchAddress("Hodo40_ChargeCalD",&Hodo40_ChargeCalD);
			inputTree->SetBranchAddress("Hodo40_TimeSlwU",&Hodo40_TimeSlwU);
			inputTree->SetBranchAddress("Hodo40_TimeSlwD",&Hodo40_TimeSlwD);
			inputTree->SetBranchAddress("Hodo40_TimeRawU",&Hodo40_TimeRawU);
			inputTree->SetBranchAddress("Hodo40_TimeRawD",&Hodo40_TimeRawD);
			inputTree->SetBranchAddress("Hodo_Multiplicity",&Hodo_Multiplicity);
			inputTree->SetBranchAddress("HodoP_Multiplicity",&HodoP_Multiplicity);
			inputTree->SetBranchAddress("HodoF_Multiplicity",&HodoF_Multiplicity);
			inputTree->SetBranchAddress("NUMBER_OF_HODO",&NUMBER_OF_HODO);
			inputTree->SetBranchAddress("AllHodo_Charge",AllHodo_Charge);
			inputTree->SetBranchAddress("AllHodo_Charge_C",AllHodo_Charge_C);
			inputTree->SetBranchAddress("AllHodo_Time",AllHodo_Time);
			inputTree->SetBranchAddress("AllHodo_Time_C",AllHodo_Time_C);
			inputTree->SetBranchAddress("AllHodo_ID",AllHodo_ID);
			inputTree->SetBranchAddress("Hodo_ID",&Hodo_ID);
			inputTree->SetBranchAddress("HOD_GlobalID",&HOD_GlobalID);
			inputTree->SetBranchAddress("Hodo_Charge",&Hodo_Charge);
			inputTree->SetBranchAddress("Hodo_Charge_C",&Hodo_Charge_C);
			inputTree->SetBranchAddress("Hodo_ChargeP",&Hodo_ChargeP);
			inputTree->SetBranchAddress("Hodo_ChargeF",&Hodo_ChargeF);
			inputTree->SetBranchAddress("Hodo_Time",&Hodo_Time);
			inputTree->SetBranchAddress("Hodo_Time_C",&Hodo_Time_C);
			inputTree->SetBranchAddress("Hodo_Z",&Hodo_Z);
			inputTree->SetBranchAddress("Hodo_AoverZ",&Hodo_AoverZ);


		}
		void setOutputBranch(TTree *tree){
			// Set branch addresses.
			tree->Branch("Hodo1_Charge",&Hodo1_Charge);
			tree->Branch("Hodo1_Charge_C",&Hodo1_Charge_C);
			tree->Branch("Hodo1_ChargeU",&Hodo1_ChargeU);
			tree->Branch("Hodo1_ChargeD",&Hodo1_ChargeD);
			tree->Branch("Hodo1_Time",&Hodo1_Time);
			tree->Branch("Hodo1_Time_C",&Hodo1_Time_C);
			tree->Branch("Hodo1_ChargeCalU",&Hodo1_ChargeCalU);
			tree->Branch("Hodo1_ChargeCalD",&Hodo1_ChargeCalD);
			tree->Branch("Hodo1_TimeSlwU",&Hodo1_TimeSlwU);
			tree->Branch("Hodo1_TimeSlwD",&Hodo1_TimeSlwD);
			tree->Branch("Hodo1_TimeRawU",&Hodo1_TimeRawU);
			tree->Branch("Hodo1_TimeRawD",&Hodo1_TimeRawD);
			tree->Branch("Hodo2_Charge",&Hodo2_Charge);
			tree->Branch("Hodo2_Charge_C",&Hodo2_Charge_C);
			tree->Branch("Hodo2_ChargeU",&Hodo2_ChargeU);
			tree->Branch("Hodo2_ChargeD",&Hodo2_ChargeD);
			tree->Branch("Hodo2_Time",&Hodo2_Time);
			tree->Branch("Hodo2_Time_C",&Hodo2_Time_C);
			tree->Branch("Hodo2_ChargeCalU",&Hodo2_ChargeCalU);
			tree->Branch("Hodo2_ChargeCalD",&Hodo2_ChargeCalD);
			tree->Branch("Hodo2_TimeSlwU",&Hodo2_TimeSlwU);
			tree->Branch("Hodo2_TimeSlwD",&Hodo2_TimeSlwD);
			tree->Branch("Hodo2_TimeRawU",&Hodo2_TimeRawU);
			tree->Branch("Hodo2_TimeRawD",&Hodo2_TimeRawD);
			tree->Branch("Hodo3_Charge",&Hodo3_Charge);
			tree->Branch("Hodo3_Charge_C",&Hodo3_Charge_C);
			tree->Branch("Hodo3_ChargeU",&Hodo3_ChargeU);
			tree->Branch("Hodo3_ChargeD",&Hodo3_ChargeD);
			tree->Branch("Hodo3_Time",&Hodo3_Time);
			tree->Branch("Hodo3_Time_C",&Hodo3_Time_C);
			tree->Branch("Hodo3_ChargeCalU",&Hodo3_ChargeCalU);
			tree->Branch("Hodo3_ChargeCalD",&Hodo3_ChargeCalD);
			tree->Branch("Hodo3_TimeSlwU",&Hodo3_TimeSlwU);
			tree->Branch("Hodo3_TimeSlwD",&Hodo3_TimeSlwD);
			tree->Branch("Hodo3_TimeRawU",&Hodo3_TimeRawU);
			tree->Branch("Hodo3_TimeRawD",&Hodo3_TimeRawD);
			tree->Branch("Hodo4_Charge",&Hodo4_Charge);
			tree->Branch("Hodo4_Charge_C",&Hodo4_Charge_C);
			tree->Branch("Hodo4_ChargeU",&Hodo4_ChargeU);
			tree->Branch("Hodo4_ChargeD",&Hodo4_ChargeD);
			tree->Branch("Hodo4_Time",&Hodo4_Time);
			tree->Branch("Hodo4_Time_C",&Hodo4_Time_C);
			tree->Branch("Hodo4_ChargeCalU",&Hodo4_ChargeCalU);
			tree->Branch("Hodo4_ChargeCalD",&Hodo4_ChargeCalD);
			tree->Branch("Hodo4_TimeSlwU",&Hodo4_TimeSlwU);
			tree->Branch("Hodo4_TimeSlwD",&Hodo4_TimeSlwD);
			tree->Branch("Hodo4_TimeRawU",&Hodo4_TimeRawU);
			tree->Branch("Hodo4_TimeRawD",&Hodo4_TimeRawD);
			tree->Branch("Hodo5_Charge",&Hodo5_Charge);
			tree->Branch("Hodo5_Charge_C",&Hodo5_Charge_C);
			tree->Branch("Hodo5_ChargeU",&Hodo5_ChargeU);
			tree->Branch("Hodo5_ChargeD",&Hodo5_ChargeD);
			tree->Branch("Hodo5_Time",&Hodo5_Time);
			tree->Branch("Hodo5_Time_C",&Hodo5_Time_C);
			tree->Branch("Hodo5_ChargeCalU",&Hodo5_ChargeCalU);
			tree->Branch("Hodo5_ChargeCalD",&Hodo5_ChargeCalD);
			tree->Branch("Hodo5_TimeSlwU",&Hodo5_TimeSlwU);
			tree->Branch("Hodo5_TimeSlwD",&Hodo5_TimeSlwD);
			tree->Branch("Hodo5_TimeRawU",&Hodo5_TimeRawU);
			tree->Branch("Hodo5_TimeRawD",&Hodo5_TimeRawD);
			tree->Branch("Hodo6_Charge",&Hodo6_Charge);
			tree->Branch("Hodo6_Charge_C",&Hodo6_Charge_C);
			tree->Branch("Hodo6_ChargeU",&Hodo6_ChargeU);
			tree->Branch("Hodo6_ChargeD",&Hodo6_ChargeD);
			tree->Branch("Hodo6_Time",&Hodo6_Time);
			tree->Branch("Hodo6_Time_C",&Hodo6_Time_C);
			tree->Branch("Hodo6_ChargeCalU",&Hodo6_ChargeCalU);
			tree->Branch("Hodo6_ChargeCalD",&Hodo6_ChargeCalD);
			tree->Branch("Hodo6_TimeSlwU",&Hodo6_TimeSlwU);
			tree->Branch("Hodo6_TimeSlwD",&Hodo6_TimeSlwD);
			tree->Branch("Hodo6_TimeRawU",&Hodo6_TimeRawU);
			tree->Branch("Hodo6_TimeRawD",&Hodo6_TimeRawD);
			tree->Branch("Hodo7_Charge",&Hodo7_Charge);
			tree->Branch("Hodo7_Charge_C",&Hodo7_Charge_C);
			tree->Branch("Hodo7_ChargeU",&Hodo7_ChargeU);
			tree->Branch("Hodo7_ChargeD",&Hodo7_ChargeD);
			tree->Branch("Hodo7_Time",&Hodo7_Time);
			tree->Branch("Hodo7_Time_C",&Hodo7_Time_C);
			tree->Branch("Hodo7_ChargeCalU",&Hodo7_ChargeCalU);
			tree->Branch("Hodo7_ChargeCalD",&Hodo7_ChargeCalD);
			tree->Branch("Hodo7_TimeSlwU",&Hodo7_TimeSlwU);
			tree->Branch("Hodo7_TimeSlwD",&Hodo7_TimeSlwD);
			tree->Branch("Hodo7_TimeRawU",&Hodo7_TimeRawU);
			tree->Branch("Hodo7_TimeRawD",&Hodo7_TimeRawD);
			tree->Branch("Hodo8_Charge",&Hodo8_Charge);
			tree->Branch("Hodo8_Charge_C",&Hodo8_Charge_C);
			tree->Branch("Hodo8_ChargeU",&Hodo8_ChargeU);
			tree->Branch("Hodo8_ChargeD",&Hodo8_ChargeD);
			tree->Branch("Hodo8_Time",&Hodo8_Time);
			tree->Branch("Hodo8_Time_C",&Hodo8_Time_C);
			tree->Branch("Hodo8_ChargeCalU",&Hodo8_ChargeCalU);
			tree->Branch("Hodo8_ChargeCalD",&Hodo8_ChargeCalD);
			tree->Branch("Hodo8_TimeSlwU",&Hodo8_TimeSlwU);
			tree->Branch("Hodo8_TimeSlwD",&Hodo8_TimeSlwD);
			tree->Branch("Hodo8_TimeRawU",&Hodo8_TimeRawU);
			tree->Branch("Hodo8_TimeRawD",&Hodo8_TimeRawD);
			tree->Branch("Hodo9_Charge",&Hodo9_Charge);
			tree->Branch("Hodo9_Charge_C",&Hodo9_Charge_C);
			tree->Branch("Hodo9_ChargeU",&Hodo9_ChargeU);
			tree->Branch("Hodo9_ChargeD",&Hodo9_ChargeD);
			tree->Branch("Hodo9_Time",&Hodo9_Time);
			tree->Branch("Hodo9_Time_C",&Hodo9_Time_C);
			tree->Branch("Hodo9_ChargeCalU",&Hodo9_ChargeCalU);
			tree->Branch("Hodo9_ChargeCalD",&Hodo9_ChargeCalD);
			tree->Branch("Hodo9_TimeSlwU",&Hodo9_TimeSlwU);
			tree->Branch("Hodo9_TimeSlwD",&Hodo9_TimeSlwD);
			tree->Branch("Hodo9_TimeRawU",&Hodo9_TimeRawU);
			tree->Branch("Hodo9_TimeRawD",&Hodo9_TimeRawD);
			tree->Branch("Hodo10_Charge",&Hodo10_Charge);
			tree->Branch("Hodo10_Charge_C",&Hodo10_Charge_C);
			tree->Branch("Hodo10_ChargeU",&Hodo10_ChargeU);
			tree->Branch("Hodo10_ChargeD",&Hodo10_ChargeD);
			tree->Branch("Hodo10_Time",&Hodo10_Time);
			tree->Branch("Hodo10_Time_C",&Hodo10_Time_C);
			tree->Branch("Hodo10_ChargeCalU",&Hodo10_ChargeCalU);
			tree->Branch("Hodo10_ChargeCalD",&Hodo10_ChargeCalD);
			tree->Branch("Hodo10_TimeSlwU",&Hodo10_TimeSlwU);
			tree->Branch("Hodo10_TimeSlwD",&Hodo10_TimeSlwD);
			tree->Branch("Hodo10_TimeRawU",&Hodo10_TimeRawU);
			tree->Branch("Hodo10_TimeRawD",&Hodo10_TimeRawD);
			tree->Branch("Hodo11_Charge",&Hodo11_Charge);
			tree->Branch("Hodo11_Charge_C",&Hodo11_Charge_C);
			tree->Branch("Hodo11_ChargeU",&Hodo11_ChargeU);
			tree->Branch("Hodo11_ChargeD",&Hodo11_ChargeD);
			tree->Branch("Hodo11_Time",&Hodo11_Time);
			tree->Branch("Hodo11_Time_C",&Hodo11_Time_C);
			tree->Branch("Hodo11_ChargeCalU",&Hodo11_ChargeCalU);
			tree->Branch("Hodo11_ChargeCalD",&Hodo11_ChargeCalD);
			tree->Branch("Hodo11_TimeSlwU",&Hodo11_TimeSlwU);
			tree->Branch("Hodo11_TimeSlwD",&Hodo11_TimeSlwD);
			tree->Branch("Hodo11_TimeRawU",&Hodo11_TimeRawU);
			tree->Branch("Hodo11_TimeRawD",&Hodo11_TimeRawD);
			tree->Branch("Hodo12_Charge",&Hodo12_Charge);
			tree->Branch("Hodo12_Charge_C",&Hodo12_Charge_C);
			tree->Branch("Hodo12_ChargeU",&Hodo12_ChargeU);
			tree->Branch("Hodo12_ChargeD",&Hodo12_ChargeD);
			tree->Branch("Hodo12_Time",&Hodo12_Time);
			tree->Branch("Hodo12_Time_C",&Hodo12_Time_C);
			tree->Branch("Hodo12_ChargeCalU",&Hodo12_ChargeCalU);
			tree->Branch("Hodo12_ChargeCalD",&Hodo12_ChargeCalD);
			tree->Branch("Hodo12_TimeSlwU",&Hodo12_TimeSlwU);
			tree->Branch("Hodo12_TimeSlwD",&Hodo12_TimeSlwD);
			tree->Branch("Hodo12_TimeRawU",&Hodo12_TimeRawU);
			tree->Branch("Hodo12_TimeRawD",&Hodo12_TimeRawD);
			tree->Branch("Hodo13_Charge",&Hodo13_Charge);
			tree->Branch("Hodo13_Charge_C",&Hodo13_Charge_C);
			tree->Branch("Hodo13_ChargeU",&Hodo13_ChargeU);
			tree->Branch("Hodo13_ChargeD",&Hodo13_ChargeD);
			tree->Branch("Hodo13_Time",&Hodo13_Time);
			tree->Branch("Hodo13_Time_C",&Hodo13_Time_C);
			tree->Branch("Hodo13_ChargeCalU",&Hodo13_ChargeCalU);
			tree->Branch("Hodo13_ChargeCalD",&Hodo13_ChargeCalD);
			tree->Branch("Hodo13_TimeSlwU",&Hodo13_TimeSlwU);
			tree->Branch("Hodo13_TimeSlwD",&Hodo13_TimeSlwD);
			tree->Branch("Hodo13_TimeRawU",&Hodo13_TimeRawU);
			tree->Branch("Hodo13_TimeRawD",&Hodo13_TimeRawD);
			tree->Branch("Hodo14_Charge",&Hodo14_Charge);
			tree->Branch("Hodo14_Charge_C",&Hodo14_Charge_C);
			tree->Branch("Hodo14_ChargeU",&Hodo14_ChargeU);
			tree->Branch("Hodo14_ChargeD",&Hodo14_ChargeD);
			tree->Branch("Hodo14_Time",&Hodo14_Time);
			tree->Branch("Hodo14_Time_C",&Hodo14_Time_C);
			tree->Branch("Hodo14_ChargeCalU",&Hodo14_ChargeCalU);
			tree->Branch("Hodo14_ChargeCalD",&Hodo14_ChargeCalD);
			tree->Branch("Hodo14_TimeSlwU",&Hodo14_TimeSlwU);
			tree->Branch("Hodo14_TimeSlwD",&Hodo14_TimeSlwD);
			tree->Branch("Hodo14_TimeRawU",&Hodo14_TimeRawU);
			tree->Branch("Hodo14_TimeRawD",&Hodo14_TimeRawD);
			tree->Branch("Hodo15_Charge",&Hodo15_Charge);
			tree->Branch("Hodo15_Charge_C",&Hodo15_Charge_C);
			tree->Branch("Hodo15_ChargeU",&Hodo15_ChargeU);
			tree->Branch("Hodo15_ChargeD",&Hodo15_ChargeD);
			tree->Branch("Hodo15_Time",&Hodo15_Time);
			tree->Branch("Hodo15_Time_C",&Hodo15_Time_C);
			tree->Branch("Hodo15_ChargeCalU",&Hodo15_ChargeCalU);
			tree->Branch("Hodo15_ChargeCalD",&Hodo15_ChargeCalD);
			tree->Branch("Hodo15_TimeSlwU",&Hodo15_TimeSlwU);
			tree->Branch("Hodo15_TimeSlwD",&Hodo15_TimeSlwD);
			tree->Branch("Hodo15_TimeRawU",&Hodo15_TimeRawU);
			tree->Branch("Hodo15_TimeRawD",&Hodo15_TimeRawD);
			tree->Branch("Hodo16_Charge",&Hodo16_Charge);
			tree->Branch("Hodo16_Charge_C",&Hodo16_Charge_C);
			tree->Branch("Hodo16_ChargeU",&Hodo16_ChargeU);
			tree->Branch("Hodo16_ChargeD",&Hodo16_ChargeD);
			tree->Branch("Hodo16_Time",&Hodo16_Time);
			tree->Branch("Hodo16_Time_C",&Hodo16_Time_C);
			tree->Branch("Hodo16_ChargeCalU",&Hodo16_ChargeCalU);
			tree->Branch("Hodo16_ChargeCalD",&Hodo16_ChargeCalD);
			tree->Branch("Hodo16_TimeSlwU",&Hodo16_TimeSlwU);
			tree->Branch("Hodo16_TimeSlwD",&Hodo16_TimeSlwD);
			tree->Branch("Hodo16_TimeRawU",&Hodo16_TimeRawU);
			tree->Branch("Hodo16_TimeRawD",&Hodo16_TimeRawD);
			tree->Branch("Hodo17_Charge",&Hodo17_Charge);
			tree->Branch("Hodo17_Charge_C",&Hodo17_Charge_C);
			tree->Branch("Hodo17_ChargeU",&Hodo17_ChargeU);
			tree->Branch("Hodo17_ChargeD",&Hodo17_ChargeD);
			tree->Branch("Hodo17_Time",&Hodo17_Time);
			tree->Branch("Hodo17_Time_C",&Hodo17_Time_C);
			tree->Branch("Hodo17_ChargeCalU",&Hodo17_ChargeCalU);
			tree->Branch("Hodo17_ChargeCalD",&Hodo17_ChargeCalD);
			tree->Branch("Hodo17_TimeSlwU",&Hodo17_TimeSlwU);
			tree->Branch("Hodo17_TimeSlwD",&Hodo17_TimeSlwD);
			tree->Branch("Hodo17_TimeRawU",&Hodo17_TimeRawU);
			tree->Branch("Hodo17_TimeRawD",&Hodo17_TimeRawD);
			tree->Branch("Hodo18_Charge",&Hodo18_Charge);
			tree->Branch("Hodo18_Charge_C",&Hodo18_Charge_C);
			tree->Branch("Hodo18_ChargeU",&Hodo18_ChargeU);
			tree->Branch("Hodo18_ChargeD",&Hodo18_ChargeD);
			tree->Branch("Hodo18_Time",&Hodo18_Time);
			tree->Branch("Hodo18_Time_C",&Hodo18_Time_C);
			tree->Branch("Hodo18_ChargeCalU",&Hodo18_ChargeCalU);
			tree->Branch("Hodo18_ChargeCalD",&Hodo18_ChargeCalD);
			tree->Branch("Hodo18_TimeSlwU",&Hodo18_TimeSlwU);
			tree->Branch("Hodo18_TimeSlwD",&Hodo18_TimeSlwD);
			tree->Branch("Hodo18_TimeRawU",&Hodo18_TimeRawU);
			tree->Branch("Hodo18_TimeRawD",&Hodo18_TimeRawD);
			tree->Branch("Hodo19_Charge",&Hodo19_Charge);
			tree->Branch("Hodo19_Charge_C",&Hodo19_Charge_C);
			tree->Branch("Hodo19_ChargeU",&Hodo19_ChargeU);
			tree->Branch("Hodo19_ChargeD",&Hodo19_ChargeD);
			tree->Branch("Hodo19_Time",&Hodo19_Time);
			tree->Branch("Hodo19_Time_C",&Hodo19_Time_C);
			tree->Branch("Hodo19_ChargeCalU",&Hodo19_ChargeCalU);
			tree->Branch("Hodo19_ChargeCalD",&Hodo19_ChargeCalD);
			tree->Branch("Hodo19_TimeSlwU",&Hodo19_TimeSlwU);
			tree->Branch("Hodo19_TimeSlwD",&Hodo19_TimeSlwD);
			tree->Branch("Hodo19_TimeRawU",&Hodo19_TimeRawU);
			tree->Branch("Hodo19_TimeRawD",&Hodo19_TimeRawD);
			tree->Branch("Hodo20_Charge",&Hodo20_Charge);
			tree->Branch("Hodo20_Charge_C",&Hodo20_Charge_C);
			tree->Branch("Hodo20_ChargeU",&Hodo20_ChargeU);
			tree->Branch("Hodo20_ChargeD",&Hodo20_ChargeD);
			tree->Branch("Hodo20_Time",&Hodo20_Time);
			tree->Branch("Hodo20_Time_C",&Hodo20_Time_C);
			tree->Branch("Hodo20_ChargeCalU",&Hodo20_ChargeCalU);
			tree->Branch("Hodo20_ChargeCalD",&Hodo20_ChargeCalD);
			tree->Branch("Hodo20_TimeSlwU",&Hodo20_TimeSlwU);
			tree->Branch("Hodo20_TimeSlwD",&Hodo20_TimeSlwD);
			tree->Branch("Hodo20_TimeRawU",&Hodo20_TimeRawU);
			tree->Branch("Hodo20_TimeRawD",&Hodo20_TimeRawD);
			tree->Branch("Hodo21_Charge",&Hodo21_Charge);
			tree->Branch("Hodo21_Charge_C",&Hodo21_Charge_C);
			tree->Branch("Hodo21_ChargeU",&Hodo21_ChargeU);
			tree->Branch("Hodo21_ChargeD",&Hodo21_ChargeD);
			tree->Branch("Hodo21_Time",&Hodo21_Time);
			tree->Branch("Hodo21_Time_C",&Hodo21_Time_C);
			tree->Branch("Hodo21_ChargeCalU",&Hodo21_ChargeCalU);
			tree->Branch("Hodo21_ChargeCalD",&Hodo21_ChargeCalD);
			tree->Branch("Hodo21_TimeSlwU",&Hodo21_TimeSlwU);
			tree->Branch("Hodo21_TimeSlwD",&Hodo21_TimeSlwD);
			tree->Branch("Hodo21_TimeRawU",&Hodo21_TimeRawU);
			tree->Branch("Hodo21_TimeRawD",&Hodo21_TimeRawD);
			tree->Branch("Hodo22_Charge",&Hodo22_Charge);
			tree->Branch("Hodo22_Charge_C",&Hodo22_Charge_C);
			tree->Branch("Hodo22_ChargeU",&Hodo22_ChargeU);
			tree->Branch("Hodo22_ChargeD",&Hodo22_ChargeD);
			tree->Branch("Hodo22_Time",&Hodo22_Time);
			tree->Branch("Hodo22_Time_C",&Hodo22_Time_C);
			tree->Branch("Hodo22_ChargeCalU",&Hodo22_ChargeCalU);
			tree->Branch("Hodo22_ChargeCalD",&Hodo22_ChargeCalD);
			tree->Branch("Hodo22_TimeSlwU",&Hodo22_TimeSlwU);
			tree->Branch("Hodo22_TimeSlwD",&Hodo22_TimeSlwD);
			tree->Branch("Hodo22_TimeRawU",&Hodo22_TimeRawU);
			tree->Branch("Hodo22_TimeRawD",&Hodo22_TimeRawD);
			tree->Branch("Hodo23_Charge",&Hodo23_Charge);
			tree->Branch("Hodo23_Charge_C",&Hodo23_Charge_C);
			tree->Branch("Hodo23_ChargeU",&Hodo23_ChargeU);
			tree->Branch("Hodo23_ChargeD",&Hodo23_ChargeD);
			tree->Branch("Hodo23_Time",&Hodo23_Time);
			tree->Branch("Hodo23_Time_C",&Hodo23_Time_C);
			tree->Branch("Hodo23_ChargeCalU",&Hodo23_ChargeCalU);
			tree->Branch("Hodo23_ChargeCalD",&Hodo23_ChargeCalD);
			tree->Branch("Hodo23_TimeSlwU",&Hodo23_TimeSlwU);
			tree->Branch("Hodo23_TimeSlwD",&Hodo23_TimeSlwD);
			tree->Branch("Hodo23_TimeRawU",&Hodo23_TimeRawU);
			tree->Branch("Hodo23_TimeRawD",&Hodo23_TimeRawD);
			tree->Branch("Hodo24_Charge",&Hodo24_Charge);
			tree->Branch("Hodo24_Charge_C",&Hodo24_Charge_C);
			tree->Branch("Hodo24_ChargeU",&Hodo24_ChargeU);
			tree->Branch("Hodo24_ChargeD",&Hodo24_ChargeD);
			tree->Branch("Hodo24_Time",&Hodo24_Time);
			tree->Branch("Hodo24_Time_C",&Hodo24_Time_C);
			tree->Branch("Hodo24_ChargeCalU",&Hodo24_ChargeCalU);
			tree->Branch("Hodo24_ChargeCalD",&Hodo24_ChargeCalD);
			tree->Branch("Hodo24_TimeSlwU",&Hodo24_TimeSlwU);
			tree->Branch("Hodo24_TimeSlwD",&Hodo24_TimeSlwD);
			tree->Branch("Hodo24_TimeRawU",&Hodo24_TimeRawU);
			tree->Branch("Hodo24_TimeRawD",&Hodo24_TimeRawD);
			tree->Branch("Hodo25_Charge",&Hodo25_Charge);
			tree->Branch("Hodo25_Charge_C",&Hodo25_Charge_C);
			tree->Branch("Hodo25_ChargeU",&Hodo25_ChargeU);
			tree->Branch("Hodo25_ChargeD",&Hodo25_ChargeD);
			tree->Branch("Hodo25_Time",&Hodo25_Time);
			tree->Branch("Hodo25_Time_C",&Hodo25_Time_C);
			tree->Branch("Hodo25_ChargeCalU",&Hodo25_ChargeCalU);
			tree->Branch("Hodo25_ChargeCalD",&Hodo25_ChargeCalD);
			tree->Branch("Hodo25_TimeSlwU",&Hodo25_TimeSlwU);
			tree->Branch("Hodo25_TimeSlwD",&Hodo25_TimeSlwD);
			tree->Branch("Hodo25_TimeRawU",&Hodo25_TimeRawU);
			tree->Branch("Hodo25_TimeRawD",&Hodo25_TimeRawD);
			tree->Branch("Hodo26_Charge",&Hodo26_Charge);
			tree->Branch("Hodo26_Charge_C",&Hodo26_Charge_C);
			tree->Branch("Hodo26_ChargeU",&Hodo26_ChargeU);
			tree->Branch("Hodo26_ChargeD",&Hodo26_ChargeD);
			tree->Branch("Hodo26_Time",&Hodo26_Time);
			tree->Branch("Hodo26_Time_C",&Hodo26_Time_C);
			tree->Branch("Hodo26_ChargeCalU",&Hodo26_ChargeCalU);
			tree->Branch("Hodo26_ChargeCalD",&Hodo26_ChargeCalD);
			tree->Branch("Hodo26_TimeSlwU",&Hodo26_TimeSlwU);
			tree->Branch("Hodo26_TimeSlwD",&Hodo26_TimeSlwD);
			tree->Branch("Hodo26_TimeRawU",&Hodo26_TimeRawU);
			tree->Branch("Hodo26_TimeRawD",&Hodo26_TimeRawD);
			tree->Branch("Hodo27_Charge",&Hodo27_Charge);
			tree->Branch("Hodo27_Charge_C",&Hodo27_Charge_C);
			tree->Branch("Hodo27_ChargeU",&Hodo27_ChargeU);
			tree->Branch("Hodo27_ChargeD",&Hodo27_ChargeD);
			tree->Branch("Hodo27_Time",&Hodo27_Time);
			tree->Branch("Hodo27_Time_C",&Hodo27_Time_C);
			tree->Branch("Hodo27_ChargeCalU",&Hodo27_ChargeCalU);
			tree->Branch("Hodo27_ChargeCalD",&Hodo27_ChargeCalD);
			tree->Branch("Hodo27_TimeSlwU",&Hodo27_TimeSlwU);
			tree->Branch("Hodo27_TimeSlwD",&Hodo27_TimeSlwD);
			tree->Branch("Hodo27_TimeRawU",&Hodo27_TimeRawU);
			tree->Branch("Hodo27_TimeRawD",&Hodo27_TimeRawD);
			tree->Branch("Hodo28_Charge",&Hodo28_Charge);
			tree->Branch("Hodo28_Charge_C",&Hodo28_Charge_C);
			tree->Branch("Hodo28_ChargeU",&Hodo28_ChargeU);
			tree->Branch("Hodo28_ChargeD",&Hodo28_ChargeD);
			tree->Branch("Hodo28_Time",&Hodo28_Time);
			tree->Branch("Hodo28_Time_C",&Hodo28_Time_C);
			tree->Branch("Hodo28_ChargeCalU",&Hodo28_ChargeCalU);
			tree->Branch("Hodo28_ChargeCalD",&Hodo28_ChargeCalD);
			tree->Branch("Hodo28_TimeSlwU",&Hodo28_TimeSlwU);
			tree->Branch("Hodo28_TimeSlwD",&Hodo28_TimeSlwD);
			tree->Branch("Hodo28_TimeRawU",&Hodo28_TimeRawU);
			tree->Branch("Hodo28_TimeRawD",&Hodo28_TimeRawD);
			tree->Branch("Hodo29_Charge",&Hodo29_Charge);
			tree->Branch("Hodo29_Charge_C",&Hodo29_Charge_C);
			tree->Branch("Hodo29_ChargeU",&Hodo29_ChargeU);
			tree->Branch("Hodo29_ChargeD",&Hodo29_ChargeD);
			tree->Branch("Hodo29_Time",&Hodo29_Time);
			tree->Branch("Hodo29_Time_C",&Hodo29_Time_C);
			tree->Branch("Hodo29_ChargeCalU",&Hodo29_ChargeCalU);
			tree->Branch("Hodo29_ChargeCalD",&Hodo29_ChargeCalD);
			tree->Branch("Hodo29_TimeSlwU",&Hodo29_TimeSlwU);
			tree->Branch("Hodo29_TimeSlwD",&Hodo29_TimeSlwD);
			tree->Branch("Hodo29_TimeRawU",&Hodo29_TimeRawU);
			tree->Branch("Hodo29_TimeRawD",&Hodo29_TimeRawD);
			tree->Branch("Hodo30_Charge",&Hodo30_Charge);
			tree->Branch("Hodo30_Charge_C",&Hodo30_Charge_C);
			tree->Branch("Hodo30_ChargeU",&Hodo30_ChargeU);
			tree->Branch("Hodo30_ChargeD",&Hodo30_ChargeD);
			tree->Branch("Hodo30_Time",&Hodo30_Time);
			tree->Branch("Hodo30_Time_C",&Hodo30_Time_C);
			tree->Branch("Hodo30_ChargeCalU",&Hodo30_ChargeCalU);
			tree->Branch("Hodo30_ChargeCalD",&Hodo30_ChargeCalD);
			tree->Branch("Hodo30_TimeSlwU",&Hodo30_TimeSlwU);
			tree->Branch("Hodo30_TimeSlwD",&Hodo30_TimeSlwD);
			tree->Branch("Hodo30_TimeRawU",&Hodo30_TimeRawU);
			tree->Branch("Hodo30_TimeRawD",&Hodo30_TimeRawD);
			tree->Branch("Hodo31_Charge",&Hodo31_Charge);
			tree->Branch("Hodo31_Charge_C",&Hodo31_Charge_C);
			tree->Branch("Hodo31_ChargeU",&Hodo31_ChargeU);
			tree->Branch("Hodo31_ChargeD",&Hodo31_ChargeD);
			tree->Branch("Hodo31_Time",&Hodo31_Time);
			tree->Branch("Hodo31_Time_C",&Hodo31_Time_C);
			tree->Branch("Hodo31_ChargeCalU",&Hodo31_ChargeCalU);
			tree->Branch("Hodo31_ChargeCalD",&Hodo31_ChargeCalD);
			tree->Branch("Hodo31_TimeSlwU",&Hodo31_TimeSlwU);
			tree->Branch("Hodo31_TimeSlwD",&Hodo31_TimeSlwD);
			tree->Branch("Hodo31_TimeRawU",&Hodo31_TimeRawU);
			tree->Branch("Hodo31_TimeRawD",&Hodo31_TimeRawD);
			tree->Branch("Hodo32_Charge",&Hodo32_Charge);
			tree->Branch("Hodo32_Charge_C",&Hodo32_Charge_C);
			tree->Branch("Hodo32_ChargeU",&Hodo32_ChargeU);
			tree->Branch("Hodo32_ChargeD",&Hodo32_ChargeD);
			tree->Branch("Hodo32_Time",&Hodo32_Time);
			tree->Branch("Hodo32_Time_C",&Hodo32_Time_C);
			tree->Branch("Hodo32_ChargeCalU",&Hodo32_ChargeCalU);
			tree->Branch("Hodo32_ChargeCalD",&Hodo32_ChargeCalD);
			tree->Branch("Hodo32_TimeSlwU",&Hodo32_TimeSlwU);
			tree->Branch("Hodo32_TimeSlwD",&Hodo32_TimeSlwD);
			tree->Branch("Hodo32_TimeRawU",&Hodo32_TimeRawU);
			tree->Branch("Hodo32_TimeRawD",&Hodo32_TimeRawD);
			tree->Branch("Hodo33_Charge",&Hodo33_Charge);
			tree->Branch("Hodo33_Charge_C",&Hodo33_Charge_C);
			tree->Branch("Hodo33_ChargeU",&Hodo33_ChargeU);
			tree->Branch("Hodo33_ChargeD",&Hodo33_ChargeD);
			tree->Branch("Hodo33_Time",&Hodo33_Time);
			tree->Branch("Hodo33_Time_C",&Hodo33_Time_C);
			tree->Branch("Hodo33_ChargeCalU",&Hodo33_ChargeCalU);
			tree->Branch("Hodo33_ChargeCalD",&Hodo33_ChargeCalD);
			tree->Branch("Hodo33_TimeSlwU",&Hodo33_TimeSlwU);
			tree->Branch("Hodo33_TimeSlwD",&Hodo33_TimeSlwD);
			tree->Branch("Hodo33_TimeRawU",&Hodo33_TimeRawU);
			tree->Branch("Hodo33_TimeRawD",&Hodo33_TimeRawD);
			tree->Branch("Hodo34_Charge",&Hodo34_Charge);
			tree->Branch("Hodo34_Charge_C",&Hodo34_Charge_C);
			tree->Branch("Hodo34_ChargeU",&Hodo34_ChargeU);
			tree->Branch("Hodo34_ChargeD",&Hodo34_ChargeD);
			tree->Branch("Hodo34_Time",&Hodo34_Time);
			tree->Branch("Hodo34_Time_C",&Hodo34_Time_C);
			tree->Branch("Hodo34_ChargeCalU",&Hodo34_ChargeCalU);
			tree->Branch("Hodo34_ChargeCalD",&Hodo34_ChargeCalD);
			tree->Branch("Hodo34_TimeSlwU",&Hodo34_TimeSlwU);
			tree->Branch("Hodo34_TimeSlwD",&Hodo34_TimeSlwD);
			tree->Branch("Hodo34_TimeRawU",&Hodo34_TimeRawU);
			tree->Branch("Hodo34_TimeRawD",&Hodo34_TimeRawD);
			tree->Branch("Hodo35_Charge",&Hodo35_Charge);
			tree->Branch("Hodo35_Charge_C",&Hodo35_Charge_C);
			tree->Branch("Hodo35_ChargeU",&Hodo35_ChargeU);
			tree->Branch("Hodo35_ChargeD",&Hodo35_ChargeD);
			tree->Branch("Hodo35_Time",&Hodo35_Time);
			tree->Branch("Hodo35_Time_C",&Hodo35_Time_C);
			tree->Branch("Hodo35_ChargeCalU",&Hodo35_ChargeCalU);
			tree->Branch("Hodo35_ChargeCalD",&Hodo35_ChargeCalD);
			tree->Branch("Hodo35_TimeSlwU",&Hodo35_TimeSlwU);
			tree->Branch("Hodo35_TimeSlwD",&Hodo35_TimeSlwD);
			tree->Branch("Hodo35_TimeRawU",&Hodo35_TimeRawU);
			tree->Branch("Hodo35_TimeRawD",&Hodo35_TimeRawD);
			tree->Branch("Hodo36_Charge",&Hodo36_Charge);
			tree->Branch("Hodo36_Charge_C",&Hodo36_Charge_C);
			tree->Branch("Hodo36_ChargeU",&Hodo36_ChargeU);
			tree->Branch("Hodo36_ChargeD",&Hodo36_ChargeD);
			tree->Branch("Hodo36_Time",&Hodo36_Time);
			tree->Branch("Hodo36_Time_C",&Hodo36_Time_C);
			tree->Branch("Hodo36_ChargeCalU",&Hodo36_ChargeCalU);
			tree->Branch("Hodo36_ChargeCalD",&Hodo36_ChargeCalD);
			tree->Branch("Hodo36_TimeSlwU",&Hodo36_TimeSlwU);
			tree->Branch("Hodo36_TimeSlwD",&Hodo36_TimeSlwD);
			tree->Branch("Hodo36_TimeRawU",&Hodo36_TimeRawU);
			tree->Branch("Hodo36_TimeRawD",&Hodo36_TimeRawD);
			tree->Branch("Hodo37_Charge",&Hodo37_Charge);
			tree->Branch("Hodo37_Charge_C",&Hodo37_Charge_C);
			tree->Branch("Hodo37_ChargeU",&Hodo37_ChargeU);
			tree->Branch("Hodo37_ChargeD",&Hodo37_ChargeD);
			tree->Branch("Hodo37_Time",&Hodo37_Time);
			tree->Branch("Hodo37_Time_C",&Hodo37_Time_C);
			tree->Branch("Hodo37_ChargeCalU",&Hodo37_ChargeCalU);
			tree->Branch("Hodo37_ChargeCalD",&Hodo37_ChargeCalD);
			tree->Branch("Hodo37_TimeSlwU",&Hodo37_TimeSlwU);
			tree->Branch("Hodo37_TimeSlwD",&Hodo37_TimeSlwD);
			tree->Branch("Hodo37_TimeRawU",&Hodo37_TimeRawU);
			tree->Branch("Hodo37_TimeRawD",&Hodo37_TimeRawD);
			tree->Branch("Hodo38_Charge",&Hodo38_Charge);
			tree->Branch("Hodo38_Charge_C",&Hodo38_Charge_C);
			tree->Branch("Hodo38_ChargeU",&Hodo38_ChargeU);
			tree->Branch("Hodo38_ChargeD",&Hodo38_ChargeD);
			tree->Branch("Hodo38_Time",&Hodo38_Time);
			tree->Branch("Hodo38_Time_C",&Hodo38_Time_C);
			tree->Branch("Hodo38_ChargeCalU",&Hodo38_ChargeCalU);
			tree->Branch("Hodo38_ChargeCalD",&Hodo38_ChargeCalD);
			tree->Branch("Hodo38_TimeSlwU",&Hodo38_TimeSlwU);
			tree->Branch("Hodo38_TimeSlwD",&Hodo38_TimeSlwD);
			tree->Branch("Hodo38_TimeRawU",&Hodo38_TimeRawU);
			tree->Branch("Hodo38_TimeRawD",&Hodo38_TimeRawD);
			tree->Branch("Hodo39_Charge",&Hodo39_Charge);
			tree->Branch("Hodo39_Charge_C",&Hodo39_Charge_C);
			tree->Branch("Hodo39_ChargeU",&Hodo39_ChargeU);
			tree->Branch("Hodo39_ChargeD",&Hodo39_ChargeD);
			tree->Branch("Hodo39_Time",&Hodo39_Time);
			tree->Branch("Hodo39_Time_C",&Hodo39_Time_C);
			tree->Branch("Hodo39_ChargeCalU",&Hodo39_ChargeCalU);
			tree->Branch("Hodo39_ChargeCalD",&Hodo39_ChargeCalD);
			tree->Branch("Hodo39_TimeSlwU",&Hodo39_TimeSlwU);
			tree->Branch("Hodo39_TimeSlwD",&Hodo39_TimeSlwD);
			tree->Branch("Hodo39_TimeRawU",&Hodo39_TimeRawU);
			tree->Branch("Hodo39_TimeRawD",&Hodo39_TimeRawD);
			tree->Branch("Hodo40_Charge",&Hodo40_Charge);
			tree->Branch("Hodo40_Charge_C",&Hodo40_Charge_C);
			tree->Branch("Hodo40_ChargeU",&Hodo40_ChargeU);
			tree->Branch("Hodo40_ChargeD",&Hodo40_ChargeD);
			tree->Branch("Hodo40_Time",&Hodo40_Time);
			tree->Branch("Hodo40_Time_C",&Hodo40_Time_C);
			tree->Branch("Hodo40_ChargeCalU",&Hodo40_ChargeCalU);
			tree->Branch("Hodo40_ChargeCalD",&Hodo40_ChargeCalD);
			tree->Branch("Hodo40_TimeSlwU",&Hodo40_TimeSlwU);
			tree->Branch("Hodo40_TimeSlwD",&Hodo40_TimeSlwD);
			tree->Branch("Hodo40_TimeRawU",&Hodo40_TimeRawU);
			tree->Branch("Hodo40_TimeRawD",&Hodo40_TimeRawD);
			tree->Branch("Hodo_Multiplicity",&Hodo_Multiplicity);
			tree->Branch("HodoP_Multiplicity",&HodoP_Multiplicity);
			tree->Branch("HodoF_Multiplicity",&HodoF_Multiplicity);
			tree->Branch("NUMBER_OF_HODO",&NUMBER_OF_HODO);
			tree->Branch("AllHodo_Charge",AllHodo_Charge);
			tree->Branch("AllHodo_Charge_C",AllHodo_Charge_C);
			tree->Branch("AllHodo_Time",AllHodo_Time);
			tree->Branch("AllHodo_Time_C",AllHodo_Time_C);
			tree->Branch("AllHodo_ID",AllHodo_ID);
			tree->Branch("Hodo_ID",&Hodo_ID);
			tree->Branch("HOD_GlobalID",&HOD_GlobalID);
			tree->Branch("Hodo_Charge",&Hodo_Charge);
			tree->Branch("Hodo_Charge_C",&Hodo_Charge_C);
			tree->Branch("Hodo_ChargeP",&Hodo_ChargeP);
			tree->Branch("Hodo_ChargeF",&Hodo_ChargeF);
			tree->Branch("Hodo_Time",&Hodo_Time);
			tree->Branch("Hodo_Time_C",&Hodo_Time_C);
			tree->Branch("Hodo_Z",&Hodo_Z);
			tree->Branch("Hodo_AoverZ",&Hodo_AoverZ);

		}


		MergeHOD(){}
		MergeHOD(int run){
			env = new TEnv("configMerger.prm");
			detector = "HOD";
			treeName = "CalTreeHODO";
			runNumber = run;
		}

		//using Convert::isFileExists;
		bool isFileExists(){
			return Convert::isFileExists(detector);
			//return isFileExists(detector);
		}
		void printTotalEventNumber(){
			cout << "N of entries (HOD):\t" << inputTree->GetEntries() << endl;
		}
		void getEntry(Long64_t ientry){
			inputTree->GetEntry(ientry);
		}
		void init(){
		}

};

